
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Admin
 * 
 */
export type Admin = Prisma.AdminModel
/**
 * Model Deposit
 * 
 */
export type Deposit = Prisma.DepositModel
/**
 * Model Withdrawal
 * 
 */
export type Withdrawal = Prisma.WithdrawalModel
/**
 * Model DepositMethod
 * 
 */
export type DepositMethod = Prisma.DepositMethodModel
/**
 * Model SubscriptionPlan
 * 
 */
export type SubscriptionPlan = Prisma.SubscriptionPlanModel
/**
 * Model UserSubscription
 * 
 */
export type UserSubscription = Prisma.UserSubscriptionModel
/**
 * Model StakingOption
 * 
 */
export type StakingOption = Prisma.StakingOptionModel
/**
 * Model WalletConnection
 * 
 */
export type WalletConnection = Prisma.WalletConnectionModel
/**
 * Model Asset
 * 
 */
export type Asset = Prisma.AssetModel
/**
 * Model UserAsset
 * 
 */
export type UserAsset = Prisma.UserAssetModel
/**
 * Model UserAssetBalance
 * 
 */
export type UserAssetBalance = Prisma.UserAssetBalanceModel
/**
 * Model UserStake
 * 
 */
export type UserStake = Prisma.UserStakeModel
/**
 * Model Trade
 * 
 */
export type Trade = Prisma.TradeModel
/**
 * Model AdminAuditLog
 * 
 */
export type AdminAuditLog = Prisma.AdminAuditLogModel
/**
 * Model PostedTrade
 * 
 */
export type PostedTrade = Prisma.PostedTradeModel
/**
 * Model TraderTrade
 * 
 */
export type TraderTrade = Prisma.TraderTradeModel
/**
 * Model CopiedTrade
 * 
 */
export type CopiedTrade = Prisma.CopiedTradeModel
