
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Admin'
export type * from './models/Deposit'
export type * from './models/Withdrawal'
export type * from './models/DepositMethod'
export type * from './models/SubscriptionPlan'
export type * from './models/UserSubscription'
export type * from './models/StakingOption'
export type * from './models/WalletConnection'
export type * from './models/Asset'
export type * from './models/UserAsset'
export type * from './models/UserAssetBalance'
export type * from './models/UserStake'
export type * from './models/Trade'
export type * from './models/AdminAuditLog'
export type * from './models/PostedTrade'
export type * from './models/TraderTrade'
export type * from './models/CopiedTrade'
export type * from './commonInputTypes'