export const assetNames = {
    // Crypto tickers
    BTC: "Bitcoin",
    ETH: "Ethereum",
    SOL: "Solana",
    BCH: "Bitcoin Cash",
    LTC: "Litecoin",
    DOGE: "Dogecoin",
    USDT: "Tether",
    MATIC: "Polygon",
    AVAX: "Avalanche",
    USDC: "USD Coin",
    AAVE: "Aave",
    ALGO: "Algorand",
    ANC: "Anchor Protocol",
    APE: "ApeCoin",
    AURORA: "Aurora",
    AXS: "Axie Infinity",
    BTG: "Bitcoin Gold",
    BORING: "BoringDAO",
    ADA: "Cardano",
    XCN: "Chain",
    LINK: "Chainlink",
    CRO: "Cronos",
    DAI: "Dai",
    DASH: "Dash",
    MANA: "Decentraland",
    ETC: "Ethereum Classic",
    EVMOS: "Evmos",
    GT: "GateToken",
    LN: "Link",
    XMR: "Monero",
    NEXO: "Nexo",
    OKB: "OKB",
    OP: "Optimism",
    OGN: "Origin Protocol",
    ORN: "Orion Protocol",
    DOT: "Polkadot",
    XPR: "Proton",
    RARI: "Rarible",
    SFP: "SafePal",
    SHIB: "Shiba Inu",
    XLM: "Stellar",
    GMT: "STEPN",
    SUSHI: "SushiSwap",
    TLOS: "Telos",
    XTZ: "Tezos",
    GRT: "The Graph",
    TRX: "Tron",
    UNI: "Uniswap",
    VET: "VeChain",
    WING: "Wing Finance",
    ZEC: "Zcash",
    XRP: "XRP",
    ICP: "Internet Computer",
    VELO: "Velodrome Finance",
    HEX: "HEX",
    PNG: "Pangolin",
    RNDR: "Render Token",
    QNT: "Quant",
    HBAR: "Hedera",
    FET: "Fetch.ai",
    XDC: "XDC Network",
    BSV: "Bitcoin SV",
    TON: "Toncoin",
    PEPE: "Pepe",
    XRPH: "XRP Healthcare",
    SOLO: "Sologenic",
  
    // Stock tickers
    AAPL: "Apple Inc.",
    ABT: "Abbott Laboratories",
    ADBE: "Adobe Inc.",
    ADI: "Analog Devices",
    AEMD: "Aethlon Medical",
    AIG: "American International Group",
    AMC: "AMC Entertainment",
    AMD: "Advanced Micro Devices",
    AMT: "American Tower",
    AMZN: "Amazon.com",
    APT: "Alpha Pro Tech",
    ASML: "ASML Holding",
    ATER: "Aterian",
    AXP: "American Express",
    BA: "Boeing",
    BABA: "Alibaba Group",
    BAC: "Bank of America",
    BIDU: "Baidu",
    BMY: "Bristol-Myers Squibb",
    C: "Citigroup",
    CAT: "Caterpillar",
    CCO: "Clear Channel Outdoor",
    CEI: "Camber Energy",
    CHWY: "Chewy",
    CL: "Colgate-Palmolive",
    CLEU: "China Liberal Education",
    CMCSA: "Comcast",
    COST: "Costco Wholesale",
    CRDF: "Cardiff Oncology",
    CRM: "Salesforce",
    CSCO: "Cisco Systems",
    CVX: "Chevron",
    DIS: "Walt Disney",
    EBAY: "eBay",
    FB: "Meta Platforms",
    FSLY: "Fastly",
    GE: "General Electric",
    GEVO: "Gevo Inc.",
    GM: "General Motors",
    GOOGL: "Alphabet Inc.",
    GS: "Goldman Sachs",
    HD: "Home Depot",
    HON: "Honeywell",
    IBM: "IBM",
    INMD: "InMode Ltd.",
    INTC: "Intel",
    JNJ: "Johnson & Johnson",
    JPM: "JPMorgan Chase",
    KO: "Coca-Cola",
    LEN: "Lennar Corporation",
    LVS: "Las Vegas Sands",
    MA: "Mastercard",
    MDLZ: "Mondelez International",
    MMM: "3M Company",
    MNST: "Monster Beverage",
    MSFT: "Microsoft",
    MO: "Altria Group",
    MRIN: "Marin Software",
    MRK: "Merck & Co.",
    MS: "Morgan Stanley",
    MSI: "Motorola Solutions",
    NFLX: "Netflix",
    NKE: "Nike",
    NVDA: "NVIDIA",
    NVS: "Novartis",
    ORCL: "Oracle",
    PEP: "PepsiCo",
    PFE: "Pfizer",
    PG: "Procter & Gamble",
    PYPL: "PayPal",
    RACE: "Ferrari",
    RKLB: "Rocket Lab USA",
    RL: "Ralph Lauren",
    RWLK: "ReWalk Robotics",
    SBUX: "Starbucks",
    SNAP: "Snap Inc.",
    SSRM: "SSR Mining",
    SQ: "Block Inc. (formerly Square)",
    T: "AT&T",
    TEVA: "Teva Pharmaceutical",
    TM: "Toyota Motor",
    TMUS: "T-Mobile US",
    TRIP: "Tripadvisor",
    TSLA: "Tesla",
    TSM: "Taiwan Semiconductor Manufacturing",
    TWTR: "Twitter",
    UNH: "UnitedHealth Group",
    V: "Visa Inc.",
    VZ: "Verizon",
    WFC: "Wells Fargo",
    WMT: "Walmart",
    XOM: "ExxonMobil"
  };