
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Asset` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Asset
 * 
 */
export type AssetModel = runtime.Types.Result.DefaultSelection<Prisma.$AssetPayload>

export type AggregateAsset = {
  _count: AssetCountAggregateOutputType | null
  _avg: AssetAvgAggregateOutputType | null
  _sum: AssetSumAggregateOutputType | null
  _min: AssetMinAggregateOutputType | null
  _max: AssetMaxAggregateOutputType | null
}

export type AssetAvgAggregateOutputType = {
  priceUsd: number | null
  stakeMin: number | null
  stakeMax: number | null
  stakeRoi: number | null
  stakeCycleDays: number | null
}

export type AssetSumAggregateOutputType = {
  priceUsd: number | null
  stakeMin: number | null
  stakeMax: number | null
  stakeRoi: number | null
  stakeCycleDays: number | null
}

export type AssetMinAggregateOutputType = {
  id: string | null
  symbol: string | null
  name: string | null
  priceUsd: number | null
  logoUrl: string | null
  stakingEnabled: boolean | null
  stakeMin: number | null
  stakeMax: number | null
  stakeRoi: number | null
  stakeCycleDays: number | null
  createdAt: Date | null
}

export type AssetMaxAggregateOutputType = {
  id: string | null
  symbol: string | null
  name: string | null
  priceUsd: number | null
  logoUrl: string | null
  stakingEnabled: boolean | null
  stakeMin: number | null
  stakeMax: number | null
  stakeRoi: number | null
  stakeCycleDays: number | null
  createdAt: Date | null
}

export type AssetCountAggregateOutputType = {
  id: number
  symbol: number
  name: number
  priceUsd: number
  logoUrl: number
  stakingEnabled: number
  stakeMin: number
  stakeMax: number
  stakeRoi: number
  stakeCycleDays: number
  createdAt: number
  _all: number
}


export type AssetAvgAggregateInputType = {
  priceUsd?: true
  stakeMin?: true
  stakeMax?: true
  stakeRoi?: true
  stakeCycleDays?: true
}

export type AssetSumAggregateInputType = {
  priceUsd?: true
  stakeMin?: true
  stakeMax?: true
  stakeRoi?: true
  stakeCycleDays?: true
}

export type AssetMinAggregateInputType = {
  id?: true
  symbol?: true
  name?: true
  priceUsd?: true
  logoUrl?: true
  stakingEnabled?: true
  stakeMin?: true
  stakeMax?: true
  stakeRoi?: true
  stakeCycleDays?: true
  createdAt?: true
}

export type AssetMaxAggregateInputType = {
  id?: true
  symbol?: true
  name?: true
  priceUsd?: true
  logoUrl?: true
  stakingEnabled?: true
  stakeMin?: true
  stakeMax?: true
  stakeRoi?: true
  stakeCycleDays?: true
  createdAt?: true
}

export type AssetCountAggregateInputType = {
  id?: true
  symbol?: true
  name?: true
  priceUsd?: true
  logoUrl?: true
  stakingEnabled?: true
  stakeMin?: true
  stakeMax?: true
  stakeRoi?: true
  stakeCycleDays?: true
  createdAt?: true
  _all?: true
}

export type AssetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Asset to aggregate.
   */
  where?: Prisma.AssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assets to fetch.
   */
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Assets
  **/
  _count?: true | AssetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AssetAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AssetSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssetMaxAggregateInputType
}

export type GetAssetAggregateType<T extends AssetAggregateArgs> = {
      [P in keyof T & keyof AggregateAsset]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAsset[P]>
    : Prisma.GetScalarType<T[P], AggregateAsset[P]>
}




export type AssetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetWhereInput
  orderBy?: Prisma.AssetOrderByWithAggregationInput | Prisma.AssetOrderByWithAggregationInput[]
  by: Prisma.AssetScalarFieldEnum[] | Prisma.AssetScalarFieldEnum
  having?: Prisma.AssetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssetCountAggregateInputType | true
  _avg?: AssetAvgAggregateInputType
  _sum?: AssetSumAggregateInputType
  _min?: AssetMinAggregateInputType
  _max?: AssetMaxAggregateInputType
}

export type AssetGroupByOutputType = {
  id: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl: string | null
  stakingEnabled: boolean
  stakeMin: number | null
  stakeMax: number | null
  stakeRoi: number | null
  stakeCycleDays: number | null
  createdAt: Date
  _count: AssetCountAggregateOutputType | null
  _avg: AssetAvgAggregateOutputType | null
  _sum: AssetSumAggregateOutputType | null
  _min: AssetMinAggregateOutputType | null
  _max: AssetMaxAggregateOutputType | null
}

type GetAssetGroupByPayload<T extends AssetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssetGroupByOutputType[P]>
      }
    >
  >



export type AssetWhereInput = {
  AND?: Prisma.AssetWhereInput | Prisma.AssetWhereInput[]
  OR?: Prisma.AssetWhereInput[]
  NOT?: Prisma.AssetWhereInput | Prisma.AssetWhereInput[]
  id?: Prisma.StringFilter<"Asset"> | string
  symbol?: Prisma.StringFilter<"Asset"> | string
  name?: Prisma.StringFilter<"Asset"> | string
  priceUsd?: Prisma.FloatFilter<"Asset"> | number
  logoUrl?: Prisma.StringNullableFilter<"Asset"> | string | null
  stakingEnabled?: Prisma.BoolFilter<"Asset"> | boolean
  stakeMin?: Prisma.FloatNullableFilter<"Asset"> | number | null
  stakeMax?: Prisma.FloatNullableFilter<"Asset"> | number | null
  stakeRoi?: Prisma.FloatNullableFilter<"Asset"> | number | null
  stakeCycleDays?: Prisma.IntNullableFilter<"Asset"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Asset"> | Date | string
  userAssets?: Prisma.UserAssetListRelationFilter
  userAssetBalances?: Prisma.UserAssetBalanceListRelationFilter
  userStakes?: Prisma.UserStakeListRelationFilter
  trades?: Prisma.TradeListRelationFilter
  postedTrades?: Prisma.PostedTradeListRelationFilter
  traderTrades?: Prisma.TraderTradeListRelationFilter
}

export type AssetOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  name?: Prisma.SortOrder
  priceUsd?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  stakingEnabled?: Prisma.SortOrder
  stakeMin?: Prisma.SortOrderInput | Prisma.SortOrder
  stakeMax?: Prisma.SortOrderInput | Prisma.SortOrder
  stakeRoi?: Prisma.SortOrderInput | Prisma.SortOrder
  stakeCycleDays?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userAssets?: Prisma.UserAssetOrderByRelationAggregateInput
  userAssetBalances?: Prisma.UserAssetBalanceOrderByRelationAggregateInput
  userStakes?: Prisma.UserStakeOrderByRelationAggregateInput
  trades?: Prisma.TradeOrderByRelationAggregateInput
  postedTrades?: Prisma.PostedTradeOrderByRelationAggregateInput
  traderTrades?: Prisma.TraderTradeOrderByRelationAggregateInput
}

export type AssetWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  symbol?: string
  AND?: Prisma.AssetWhereInput | Prisma.AssetWhereInput[]
  OR?: Prisma.AssetWhereInput[]
  NOT?: Prisma.AssetWhereInput | Prisma.AssetWhereInput[]
  name?: Prisma.StringFilter<"Asset"> | string
  priceUsd?: Prisma.FloatFilter<"Asset"> | number
  logoUrl?: Prisma.StringNullableFilter<"Asset"> | string | null
  stakingEnabled?: Prisma.BoolFilter<"Asset"> | boolean
  stakeMin?: Prisma.FloatNullableFilter<"Asset"> | number | null
  stakeMax?: Prisma.FloatNullableFilter<"Asset"> | number | null
  stakeRoi?: Prisma.FloatNullableFilter<"Asset"> | number | null
  stakeCycleDays?: Prisma.IntNullableFilter<"Asset"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Asset"> | Date | string
  userAssets?: Prisma.UserAssetListRelationFilter
  userAssetBalances?: Prisma.UserAssetBalanceListRelationFilter
  userStakes?: Prisma.UserStakeListRelationFilter
  trades?: Prisma.TradeListRelationFilter
  postedTrades?: Prisma.PostedTradeListRelationFilter
  traderTrades?: Prisma.TraderTradeListRelationFilter
}, "id" | "symbol">

export type AssetOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  name?: Prisma.SortOrder
  priceUsd?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  stakingEnabled?: Prisma.SortOrder
  stakeMin?: Prisma.SortOrderInput | Prisma.SortOrder
  stakeMax?: Prisma.SortOrderInput | Prisma.SortOrder
  stakeRoi?: Prisma.SortOrderInput | Prisma.SortOrder
  stakeCycleDays?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AssetCountOrderByAggregateInput
  _avg?: Prisma.AssetAvgOrderByAggregateInput
  _max?: Prisma.AssetMaxOrderByAggregateInput
  _min?: Prisma.AssetMinOrderByAggregateInput
  _sum?: Prisma.AssetSumOrderByAggregateInput
}

export type AssetScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssetScalarWhereWithAggregatesInput | Prisma.AssetScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssetScalarWhereWithAggregatesInput | Prisma.AssetScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Asset"> | string
  symbol?: Prisma.StringWithAggregatesFilter<"Asset"> | string
  name?: Prisma.StringWithAggregatesFilter<"Asset"> | string
  priceUsd?: Prisma.FloatWithAggregatesFilter<"Asset"> | number
  logoUrl?: Prisma.StringNullableWithAggregatesFilter<"Asset"> | string | null
  stakingEnabled?: Prisma.BoolWithAggregatesFilter<"Asset"> | boolean
  stakeMin?: Prisma.FloatNullableWithAggregatesFilter<"Asset"> | number | null
  stakeMax?: Prisma.FloatNullableWithAggregatesFilter<"Asset"> | number | null
  stakeRoi?: Prisma.FloatNullableWithAggregatesFilter<"Asset"> | number | null
  stakeCycleDays?: Prisma.IntNullableWithAggregatesFilter<"Asset"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Asset"> | Date | string
}

export type AssetCreateInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeCreateNestedManyWithoutAssetInput
}

export type AssetUncheckedCreateInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetUncheckedCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeUncheckedCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeUncheckedCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeUncheckedCreateNestedManyWithoutAssetInput
}

export type AssetUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUpdateManyWithoutAssetNestedInput
}

export type AssetUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUncheckedUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUncheckedUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUncheckedUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUncheckedUpdateManyWithoutAssetNestedInput
}

export type AssetCreateManyInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
}

export type AssetUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  name?: Prisma.SortOrder
  priceUsd?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  stakingEnabled?: Prisma.SortOrder
  stakeMin?: Prisma.SortOrder
  stakeMax?: Prisma.SortOrder
  stakeRoi?: Prisma.SortOrder
  stakeCycleDays?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssetAvgOrderByAggregateInput = {
  priceUsd?: Prisma.SortOrder
  stakeMin?: Prisma.SortOrder
  stakeMax?: Prisma.SortOrder
  stakeRoi?: Prisma.SortOrder
  stakeCycleDays?: Prisma.SortOrder
}

export type AssetMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  name?: Prisma.SortOrder
  priceUsd?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  stakingEnabled?: Prisma.SortOrder
  stakeMin?: Prisma.SortOrder
  stakeMax?: Prisma.SortOrder
  stakeRoi?: Prisma.SortOrder
  stakeCycleDays?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssetMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  name?: Prisma.SortOrder
  priceUsd?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  stakingEnabled?: Prisma.SortOrder
  stakeMin?: Prisma.SortOrder
  stakeMax?: Prisma.SortOrder
  stakeRoi?: Prisma.SortOrder
  stakeCycleDays?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssetSumOrderByAggregateInput = {
  priceUsd?: Prisma.SortOrder
  stakeMin?: Prisma.SortOrder
  stakeMax?: Prisma.SortOrder
  stakeRoi?: Prisma.SortOrder
  stakeCycleDays?: Prisma.SortOrder
}

export type AssetScalarRelationFilter = {
  is?: Prisma.AssetWhereInput
  isNot?: Prisma.AssetWhereInput
}

export type AssetNullableScalarRelationFilter = {
  is?: Prisma.AssetWhereInput | null
  isNot?: Prisma.AssetWhereInput | null
}

export type AssetCreateNestedOneWithoutUserAssetsInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutUserAssetsInput, Prisma.AssetUncheckedCreateWithoutUserAssetsInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutUserAssetsInput
  connect?: Prisma.AssetWhereUniqueInput
}

export type AssetUpdateOneRequiredWithoutUserAssetsNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutUserAssetsInput, Prisma.AssetUncheckedCreateWithoutUserAssetsInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutUserAssetsInput
  upsert?: Prisma.AssetUpsertWithoutUserAssetsInput
  connect?: Prisma.AssetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetUpdateToOneWithWhereWithoutUserAssetsInput, Prisma.AssetUpdateWithoutUserAssetsInput>, Prisma.AssetUncheckedUpdateWithoutUserAssetsInput>
}

export type AssetCreateNestedOneWithoutUserAssetBalancesInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutUserAssetBalancesInput, Prisma.AssetUncheckedCreateWithoutUserAssetBalancesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutUserAssetBalancesInput
  connect?: Prisma.AssetWhereUniqueInput
}

export type AssetUpdateOneRequiredWithoutUserAssetBalancesNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutUserAssetBalancesInput, Prisma.AssetUncheckedCreateWithoutUserAssetBalancesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutUserAssetBalancesInput
  upsert?: Prisma.AssetUpsertWithoutUserAssetBalancesInput
  connect?: Prisma.AssetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetUpdateToOneWithWhereWithoutUserAssetBalancesInput, Prisma.AssetUpdateWithoutUserAssetBalancesInput>, Prisma.AssetUncheckedUpdateWithoutUserAssetBalancesInput>
}

export type AssetCreateNestedOneWithoutUserStakesInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutUserStakesInput, Prisma.AssetUncheckedCreateWithoutUserStakesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutUserStakesInput
  connect?: Prisma.AssetWhereUniqueInput
}

export type AssetUpdateOneRequiredWithoutUserStakesNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutUserStakesInput, Prisma.AssetUncheckedCreateWithoutUserStakesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutUserStakesInput
  upsert?: Prisma.AssetUpsertWithoutUserStakesInput
  connect?: Prisma.AssetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetUpdateToOneWithWhereWithoutUserStakesInput, Prisma.AssetUpdateWithoutUserStakesInput>, Prisma.AssetUncheckedUpdateWithoutUserStakesInput>
}

export type AssetCreateNestedOneWithoutTradesInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutTradesInput, Prisma.AssetUncheckedCreateWithoutTradesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutTradesInput
  connect?: Prisma.AssetWhereUniqueInput
}

export type AssetUpdateOneRequiredWithoutTradesNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutTradesInput, Prisma.AssetUncheckedCreateWithoutTradesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutTradesInput
  upsert?: Prisma.AssetUpsertWithoutTradesInput
  connect?: Prisma.AssetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetUpdateToOneWithWhereWithoutTradesInput, Prisma.AssetUpdateWithoutTradesInput>, Prisma.AssetUncheckedUpdateWithoutTradesInput>
}

export type AssetCreateNestedOneWithoutPostedTradesInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutPostedTradesInput, Prisma.AssetUncheckedCreateWithoutPostedTradesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutPostedTradesInput
  connect?: Prisma.AssetWhereUniqueInput
}

export type AssetUpdateOneWithoutPostedTradesNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutPostedTradesInput, Prisma.AssetUncheckedCreateWithoutPostedTradesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutPostedTradesInput
  upsert?: Prisma.AssetUpsertWithoutPostedTradesInput
  disconnect?: Prisma.AssetWhereInput | boolean
  delete?: Prisma.AssetWhereInput | boolean
  connect?: Prisma.AssetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetUpdateToOneWithWhereWithoutPostedTradesInput, Prisma.AssetUpdateWithoutPostedTradesInput>, Prisma.AssetUncheckedUpdateWithoutPostedTradesInput>
}

export type AssetCreateNestedOneWithoutTraderTradesInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutTraderTradesInput, Prisma.AssetUncheckedCreateWithoutTraderTradesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutTraderTradesInput
  connect?: Prisma.AssetWhereUniqueInput
}

export type AssetUpdateOneRequiredWithoutTraderTradesNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutTraderTradesInput, Prisma.AssetUncheckedCreateWithoutTraderTradesInput>
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutTraderTradesInput
  upsert?: Prisma.AssetUpsertWithoutTraderTradesInput
  connect?: Prisma.AssetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetUpdateToOneWithWhereWithoutTraderTradesInput, Prisma.AssetUpdateWithoutTraderTradesInput>, Prisma.AssetUncheckedUpdateWithoutTraderTradesInput>
}

export type AssetCreateWithoutUserAssetsInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssetBalances?: Prisma.UserAssetBalanceCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeCreateNestedManyWithoutAssetInput
}

export type AssetUncheckedCreateWithoutUserAssetsInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeUncheckedCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeUncheckedCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeUncheckedCreateNestedManyWithoutAssetInput
}

export type AssetCreateOrConnectWithoutUserAssetsInput = {
  where: Prisma.AssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetCreateWithoutUserAssetsInput, Prisma.AssetUncheckedCreateWithoutUserAssetsInput>
}

export type AssetUpsertWithoutUserAssetsInput = {
  update: Prisma.XOR<Prisma.AssetUpdateWithoutUserAssetsInput, Prisma.AssetUncheckedUpdateWithoutUserAssetsInput>
  create: Prisma.XOR<Prisma.AssetCreateWithoutUserAssetsInput, Prisma.AssetUncheckedCreateWithoutUserAssetsInput>
  where?: Prisma.AssetWhereInput
}

export type AssetUpdateToOneWithWhereWithoutUserAssetsInput = {
  where?: Prisma.AssetWhereInput
  data: Prisma.XOR<Prisma.AssetUpdateWithoutUserAssetsInput, Prisma.AssetUncheckedUpdateWithoutUserAssetsInput>
}

export type AssetUpdateWithoutUserAssetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssetBalances?: Prisma.UserAssetBalanceUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUpdateManyWithoutAssetNestedInput
}

export type AssetUncheckedUpdateWithoutUserAssetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUncheckedUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUncheckedUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUncheckedUpdateManyWithoutAssetNestedInput
}

export type AssetCreateWithoutUserAssetBalancesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeCreateNestedManyWithoutAssetInput
}

export type AssetUncheckedCreateWithoutUserAssetBalancesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetUncheckedCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeUncheckedCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeUncheckedCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeUncheckedCreateNestedManyWithoutAssetInput
}

export type AssetCreateOrConnectWithoutUserAssetBalancesInput = {
  where: Prisma.AssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetCreateWithoutUserAssetBalancesInput, Prisma.AssetUncheckedCreateWithoutUserAssetBalancesInput>
}

export type AssetUpsertWithoutUserAssetBalancesInput = {
  update: Prisma.XOR<Prisma.AssetUpdateWithoutUserAssetBalancesInput, Prisma.AssetUncheckedUpdateWithoutUserAssetBalancesInput>
  create: Prisma.XOR<Prisma.AssetCreateWithoutUserAssetBalancesInput, Prisma.AssetUncheckedCreateWithoutUserAssetBalancesInput>
  where?: Prisma.AssetWhereInput
}

export type AssetUpdateToOneWithWhereWithoutUserAssetBalancesInput = {
  where?: Prisma.AssetWhereInput
  data: Prisma.XOR<Prisma.AssetUpdateWithoutUserAssetBalancesInput, Prisma.AssetUncheckedUpdateWithoutUserAssetBalancesInput>
}

export type AssetUpdateWithoutUserAssetBalancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUpdateManyWithoutAssetNestedInput
}

export type AssetUncheckedUpdateWithoutUserAssetBalancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUncheckedUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUncheckedUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUncheckedUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUncheckedUpdateManyWithoutAssetNestedInput
}

export type AssetCreateWithoutUserStakesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeCreateNestedManyWithoutAssetInput
}

export type AssetUncheckedCreateWithoutUserStakesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetUncheckedCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeUncheckedCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeUncheckedCreateNestedManyWithoutAssetInput
}

export type AssetCreateOrConnectWithoutUserStakesInput = {
  where: Prisma.AssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetCreateWithoutUserStakesInput, Prisma.AssetUncheckedCreateWithoutUserStakesInput>
}

export type AssetUpsertWithoutUserStakesInput = {
  update: Prisma.XOR<Prisma.AssetUpdateWithoutUserStakesInput, Prisma.AssetUncheckedUpdateWithoutUserStakesInput>
  create: Prisma.XOR<Prisma.AssetCreateWithoutUserStakesInput, Prisma.AssetUncheckedCreateWithoutUserStakesInput>
  where?: Prisma.AssetWhereInput
}

export type AssetUpdateToOneWithWhereWithoutUserStakesInput = {
  where?: Prisma.AssetWhereInput
  data: Prisma.XOR<Prisma.AssetUpdateWithoutUserStakesInput, Prisma.AssetUncheckedUpdateWithoutUserStakesInput>
}

export type AssetUpdateWithoutUserStakesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUpdateManyWithoutAssetNestedInput
}

export type AssetUncheckedUpdateWithoutUserStakesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUncheckedUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUncheckedUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUncheckedUpdateManyWithoutAssetNestedInput
}

export type AssetCreateWithoutTradesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeCreateNestedManyWithoutAssetInput
}

export type AssetUncheckedCreateWithoutTradesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetUncheckedCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeUncheckedCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeUncheckedCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeUncheckedCreateNestedManyWithoutAssetInput
}

export type AssetCreateOrConnectWithoutTradesInput = {
  where: Prisma.AssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetCreateWithoutTradesInput, Prisma.AssetUncheckedCreateWithoutTradesInput>
}

export type AssetUpsertWithoutTradesInput = {
  update: Prisma.XOR<Prisma.AssetUpdateWithoutTradesInput, Prisma.AssetUncheckedUpdateWithoutTradesInput>
  create: Prisma.XOR<Prisma.AssetCreateWithoutTradesInput, Prisma.AssetUncheckedCreateWithoutTradesInput>
  where?: Prisma.AssetWhereInput
}

export type AssetUpdateToOneWithWhereWithoutTradesInput = {
  where?: Prisma.AssetWhereInput
  data: Prisma.XOR<Prisma.AssetUpdateWithoutTradesInput, Prisma.AssetUncheckedUpdateWithoutTradesInput>
}

export type AssetUpdateWithoutTradesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUpdateManyWithoutAssetNestedInput
}

export type AssetUncheckedUpdateWithoutTradesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUncheckedUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUncheckedUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUncheckedUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUncheckedUpdateManyWithoutAssetNestedInput
}

export type AssetCreateWithoutPostedTradesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeCreateNestedManyWithoutAssetInput
}

export type AssetUncheckedCreateWithoutPostedTradesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetUncheckedCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeUncheckedCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutAssetInput
  traderTrades?: Prisma.TraderTradeUncheckedCreateNestedManyWithoutAssetInput
}

export type AssetCreateOrConnectWithoutPostedTradesInput = {
  where: Prisma.AssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetCreateWithoutPostedTradesInput, Prisma.AssetUncheckedCreateWithoutPostedTradesInput>
}

export type AssetUpsertWithoutPostedTradesInput = {
  update: Prisma.XOR<Prisma.AssetUpdateWithoutPostedTradesInput, Prisma.AssetUncheckedUpdateWithoutPostedTradesInput>
  create: Prisma.XOR<Prisma.AssetCreateWithoutPostedTradesInput, Prisma.AssetUncheckedCreateWithoutPostedTradesInput>
  where?: Prisma.AssetWhereInput
}

export type AssetUpdateToOneWithWhereWithoutPostedTradesInput = {
  where?: Prisma.AssetWhereInput
  data: Prisma.XOR<Prisma.AssetUpdateWithoutPostedTradesInput, Prisma.AssetUncheckedUpdateWithoutPostedTradesInput>
}

export type AssetUpdateWithoutPostedTradesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUpdateManyWithoutAssetNestedInput
}

export type AssetUncheckedUpdateWithoutPostedTradesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUncheckedUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUncheckedUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutAssetNestedInput
  traderTrades?: Prisma.TraderTradeUncheckedUpdateManyWithoutAssetNestedInput
}

export type AssetCreateWithoutTraderTradesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeCreateNestedManyWithoutAssetInput
}

export type AssetUncheckedCreateWithoutTraderTradesInput = {
  id?: string
  symbol: string
  name: string
  priceUsd: number
  logoUrl?: string | null
  stakingEnabled?: boolean
  stakeMin?: number | null
  stakeMax?: number | null
  stakeRoi?: number | null
  stakeCycleDays?: number | null
  createdAt?: Date | string
  userAssets?: Prisma.UserAssetUncheckedCreateNestedManyWithoutAssetInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedCreateNestedManyWithoutAssetInput
  userStakes?: Prisma.UserStakeUncheckedCreateNestedManyWithoutAssetInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutAssetInput
  postedTrades?: Prisma.PostedTradeUncheckedCreateNestedManyWithoutAssetInput
}

export type AssetCreateOrConnectWithoutTraderTradesInput = {
  where: Prisma.AssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetCreateWithoutTraderTradesInput, Prisma.AssetUncheckedCreateWithoutTraderTradesInput>
}

export type AssetUpsertWithoutTraderTradesInput = {
  update: Prisma.XOR<Prisma.AssetUpdateWithoutTraderTradesInput, Prisma.AssetUncheckedUpdateWithoutTraderTradesInput>
  create: Prisma.XOR<Prisma.AssetCreateWithoutTraderTradesInput, Prisma.AssetUncheckedCreateWithoutTraderTradesInput>
  where?: Prisma.AssetWhereInput
}

export type AssetUpdateToOneWithWhereWithoutTraderTradesInput = {
  where?: Prisma.AssetWhereInput
  data: Prisma.XOR<Prisma.AssetUpdateWithoutTraderTradesInput, Prisma.AssetUncheckedUpdateWithoutTraderTradesInput>
}

export type AssetUpdateWithoutTraderTradesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUpdateManyWithoutAssetNestedInput
}

export type AssetUncheckedUpdateWithoutTraderTradesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  priceUsd?: Prisma.FloatFieldUpdateOperationsInput | number
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stakingEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stakeMin?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeMax?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeRoi?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stakeCycleDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAssets?: Prisma.UserAssetUncheckedUpdateManyWithoutAssetNestedInput
  userAssetBalances?: Prisma.UserAssetBalanceUncheckedUpdateManyWithoutAssetNestedInput
  userStakes?: Prisma.UserStakeUncheckedUpdateManyWithoutAssetNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutAssetNestedInput
  postedTrades?: Prisma.PostedTradeUncheckedUpdateManyWithoutAssetNestedInput
}


/**
 * Count Type AssetCountOutputType
 */

export type AssetCountOutputType = {
  userAssets: number
  userAssetBalances: number
  userStakes: number
  trades: number
  postedTrades: number
  traderTrades: number
}

export type AssetCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userAssets?: boolean | AssetCountOutputTypeCountUserAssetsArgs
  userAssetBalances?: boolean | AssetCountOutputTypeCountUserAssetBalancesArgs
  userStakes?: boolean | AssetCountOutputTypeCountUserStakesArgs
  trades?: boolean | AssetCountOutputTypeCountTradesArgs
  postedTrades?: boolean | AssetCountOutputTypeCountPostedTradesArgs
  traderTrades?: boolean | AssetCountOutputTypeCountTraderTradesArgs
}

/**
 * AssetCountOutputType without action
 */
export type AssetCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCountOutputType
   */
  select?: Prisma.AssetCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AssetCountOutputType without action
 */
export type AssetCountOutputTypeCountUserAssetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserAssetWhereInput
}

/**
 * AssetCountOutputType without action
 */
export type AssetCountOutputTypeCountUserAssetBalancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserAssetBalanceWhereInput
}

/**
 * AssetCountOutputType without action
 */
export type AssetCountOutputTypeCountUserStakesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserStakeWhereInput
}

/**
 * AssetCountOutputType without action
 */
export type AssetCountOutputTypeCountTradesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TradeWhereInput
}

/**
 * AssetCountOutputType without action
 */
export type AssetCountOutputTypeCountPostedTradesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostedTradeWhereInput
}

/**
 * AssetCountOutputType without action
 */
export type AssetCountOutputTypeCountTraderTradesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TraderTradeWhereInput
}


export type AssetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  symbol?: boolean
  name?: boolean
  priceUsd?: boolean
  logoUrl?: boolean
  stakingEnabled?: boolean
  stakeMin?: boolean
  stakeMax?: boolean
  stakeRoi?: boolean
  stakeCycleDays?: boolean
  createdAt?: boolean
  userAssets?: boolean | Prisma.Asset$userAssetsArgs<ExtArgs>
  userAssetBalances?: boolean | Prisma.Asset$userAssetBalancesArgs<ExtArgs>
  userStakes?: boolean | Prisma.Asset$userStakesArgs<ExtArgs>
  trades?: boolean | Prisma.Asset$tradesArgs<ExtArgs>
  postedTrades?: boolean | Prisma.Asset$postedTradesArgs<ExtArgs>
  traderTrades?: boolean | Prisma.Asset$traderTradesArgs<ExtArgs>
  _count?: boolean | Prisma.AssetCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["asset"]>

export type AssetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  symbol?: boolean
  name?: boolean
  priceUsd?: boolean
  logoUrl?: boolean
  stakingEnabled?: boolean
  stakeMin?: boolean
  stakeMax?: boolean
  stakeRoi?: boolean
  stakeCycleDays?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["asset"]>

export type AssetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  symbol?: boolean
  name?: boolean
  priceUsd?: boolean
  logoUrl?: boolean
  stakingEnabled?: boolean
  stakeMin?: boolean
  stakeMax?: boolean
  stakeRoi?: boolean
  stakeCycleDays?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["asset"]>

export type AssetSelectScalar = {
  id?: boolean
  symbol?: boolean
  name?: boolean
  priceUsd?: boolean
  logoUrl?: boolean
  stakingEnabled?: boolean
  stakeMin?: boolean
  stakeMax?: boolean
  stakeRoi?: boolean
  stakeCycleDays?: boolean
  createdAt?: boolean
}

export type AssetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "symbol" | "name" | "priceUsd" | "logoUrl" | "stakingEnabled" | "stakeMin" | "stakeMax" | "stakeRoi" | "stakeCycleDays" | "createdAt", ExtArgs["result"]["asset"]>
export type AssetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userAssets?: boolean | Prisma.Asset$userAssetsArgs<ExtArgs>
  userAssetBalances?: boolean | Prisma.Asset$userAssetBalancesArgs<ExtArgs>
  userStakes?: boolean | Prisma.Asset$userStakesArgs<ExtArgs>
  trades?: boolean | Prisma.Asset$tradesArgs<ExtArgs>
  postedTrades?: boolean | Prisma.Asset$postedTradesArgs<ExtArgs>
  traderTrades?: boolean | Prisma.Asset$traderTradesArgs<ExtArgs>
  _count?: boolean | Prisma.AssetCountOutputTypeDefaultArgs<ExtArgs>
}
export type AssetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AssetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AssetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Asset"
  objects: {
    userAssets: Prisma.$UserAssetPayload<ExtArgs>[]
    userAssetBalances: Prisma.$UserAssetBalancePayload<ExtArgs>[]
    userStakes: Prisma.$UserStakePayload<ExtArgs>[]
    trades: Prisma.$TradePayload<ExtArgs>[]
    postedTrades: Prisma.$PostedTradePayload<ExtArgs>[]
    traderTrades: Prisma.$TraderTradePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    symbol: string
    name: string
    priceUsd: number
    logoUrl: string | null
    stakingEnabled: boolean
    stakeMin: number | null
    stakeMax: number | null
    stakeRoi: number | null
    stakeCycleDays: number | null
    createdAt: Date
  }, ExtArgs["result"]["asset"]>
  composites: {}
}

export type AssetGetPayload<S extends boolean | null | undefined | AssetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssetPayload, S>

export type AssetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssetCountAggregateInputType | true
  }

export interface AssetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Asset'], meta: { name: 'Asset' } }
  /**
   * Find zero or one Asset that matches the filter.
   * @param {AssetFindUniqueArgs} args - Arguments to find a Asset
   * @example
   * // Get one Asset
   * const asset = await prisma.asset.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssetFindUniqueArgs>(args: Prisma.SelectSubset<T, AssetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Asset that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssetFindUniqueOrThrowArgs} args - Arguments to find a Asset
   * @example
   * // Get one Asset
   * const asset = await prisma.asset.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Asset that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetFindFirstArgs} args - Arguments to find a Asset
   * @example
   * // Get one Asset
   * const asset = await prisma.asset.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssetFindFirstArgs>(args?: Prisma.SelectSubset<T, AssetFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Asset that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetFindFirstOrThrowArgs} args - Arguments to find a Asset
   * @example
   * // Get one Asset
   * const asset = await prisma.asset.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Assets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Assets
   * const assets = await prisma.asset.findMany()
   * 
   * // Get first 10 Assets
   * const assets = await prisma.asset.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assetWithIdOnly = await prisma.asset.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AssetFindManyArgs>(args?: Prisma.SelectSubset<T, AssetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Asset.
   * @param {AssetCreateArgs} args - Arguments to create a Asset.
   * @example
   * // Create one Asset
   * const Asset = await prisma.asset.create({
   *   data: {
   *     // ... data to create a Asset
   *   }
   * })
   * 
   */
  create<T extends AssetCreateArgs>(args: Prisma.SelectSubset<T, AssetCreateArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Assets.
   * @param {AssetCreateManyArgs} args - Arguments to create many Assets.
   * @example
   * // Create many Assets
   * const asset = await prisma.asset.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssetCreateManyArgs>(args?: Prisma.SelectSubset<T, AssetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Assets and returns the data saved in the database.
   * @param {AssetCreateManyAndReturnArgs} args - Arguments to create many Assets.
   * @example
   * // Create many Assets
   * const asset = await prisma.asset.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Assets and only return the `id`
   * const assetWithIdOnly = await prisma.asset.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Asset.
   * @param {AssetDeleteArgs} args - Arguments to delete one Asset.
   * @example
   * // Delete one Asset
   * const Asset = await prisma.asset.delete({
   *   where: {
   *     // ... filter to delete one Asset
   *   }
   * })
   * 
   */
  delete<T extends AssetDeleteArgs>(args: Prisma.SelectSubset<T, AssetDeleteArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Asset.
   * @param {AssetUpdateArgs} args - Arguments to update one Asset.
   * @example
   * // Update one Asset
   * const asset = await prisma.asset.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssetUpdateArgs>(args: Prisma.SelectSubset<T, AssetUpdateArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Assets.
   * @param {AssetDeleteManyArgs} args - Arguments to filter Assets to delete.
   * @example
   * // Delete a few Assets
   * const { count } = await prisma.asset.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssetDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Assets
   * const asset = await prisma.asset.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssetUpdateManyArgs>(args: Prisma.SelectSubset<T, AssetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assets and returns the data updated in the database.
   * @param {AssetUpdateManyAndReturnArgs} args - Arguments to update many Assets.
   * @example
   * // Update many Assets
   * const asset = await prisma.asset.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Assets and only return the `id`
   * const assetWithIdOnly = await prisma.asset.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Asset.
   * @param {AssetUpsertArgs} args - Arguments to update or create a Asset.
   * @example
   * // Update or create a Asset
   * const asset = await prisma.asset.upsert({
   *   create: {
   *     // ... data to create a Asset
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Asset we want to update
   *   }
   * })
   */
  upsert<T extends AssetUpsertArgs>(args: Prisma.SelectSubset<T, AssetUpsertArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Assets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCountArgs} args - Arguments to filter Assets to count.
   * @example
   * // Count the number of Assets
   * const count = await prisma.asset.count({
   *   where: {
   *     // ... the filter for the Assets we want to count
   *   }
   * })
  **/
  count<T extends AssetCountArgs>(
    args?: Prisma.Subset<T, AssetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Asset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssetAggregateArgs>(args: Prisma.Subset<T, AssetAggregateArgs>): Prisma.PrismaPromise<GetAssetAggregateType<T>>

  /**
   * Group by Asset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssetGroupByArgs['orderBy'] }
      : { orderBy?: AssetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Asset model
 */
readonly fields: AssetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Asset.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  userAssets<T extends Prisma.Asset$userAssetsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asset$userAssetsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserAssetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  userAssetBalances<T extends Prisma.Asset$userAssetBalancesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asset$userAssetBalancesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserAssetBalancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  userStakes<T extends Prisma.Asset$userStakesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asset$userStakesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  trades<T extends Prisma.Asset$tradesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asset$tradesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  postedTrades<T extends Prisma.Asset$postedTradesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asset$postedTradesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  traderTrades<T extends Prisma.Asset$traderTradesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asset$traderTradesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TraderTradePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Asset model
 */
export interface AssetFieldRefs {
  readonly id: Prisma.FieldRef<"Asset", 'String'>
  readonly symbol: Prisma.FieldRef<"Asset", 'String'>
  readonly name: Prisma.FieldRef<"Asset", 'String'>
  readonly priceUsd: Prisma.FieldRef<"Asset", 'Float'>
  readonly logoUrl: Prisma.FieldRef<"Asset", 'String'>
  readonly stakingEnabled: Prisma.FieldRef<"Asset", 'Boolean'>
  readonly stakeMin: Prisma.FieldRef<"Asset", 'Float'>
  readonly stakeMax: Prisma.FieldRef<"Asset", 'Float'>
  readonly stakeRoi: Prisma.FieldRef<"Asset", 'Float'>
  readonly stakeCycleDays: Prisma.FieldRef<"Asset", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Asset", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Asset findUnique
 */
export type AssetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Asset to fetch.
   */
  where: Prisma.AssetWhereUniqueInput
}

/**
 * Asset findUniqueOrThrow
 */
export type AssetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Asset to fetch.
   */
  where: Prisma.AssetWhereUniqueInput
}

/**
 * Asset findFirst
 */
export type AssetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Asset to fetch.
   */
  where?: Prisma.AssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assets to fetch.
   */
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assets.
   */
  cursor?: Prisma.AssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assets.
   */
  distinct?: Prisma.AssetScalarFieldEnum | Prisma.AssetScalarFieldEnum[]
}

/**
 * Asset findFirstOrThrow
 */
export type AssetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Asset to fetch.
   */
  where?: Prisma.AssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assets to fetch.
   */
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assets.
   */
  cursor?: Prisma.AssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assets.
   */
  distinct?: Prisma.AssetScalarFieldEnum | Prisma.AssetScalarFieldEnum[]
}

/**
 * Asset findMany
 */
export type AssetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Assets to fetch.
   */
  where?: Prisma.AssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assets to fetch.
   */
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Assets.
   */
  cursor?: Prisma.AssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assets.
   */
  skip?: number
  distinct?: Prisma.AssetScalarFieldEnum | Prisma.AssetScalarFieldEnum[]
}

/**
 * Asset create
 */
export type AssetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * The data needed to create a Asset.
   */
  data: Prisma.XOR<Prisma.AssetCreateInput, Prisma.AssetUncheckedCreateInput>
}

/**
 * Asset createMany
 */
export type AssetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Assets.
   */
  data: Prisma.AssetCreateManyInput | Prisma.AssetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Asset createManyAndReturn
 */
export type AssetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * The data used to create many Assets.
   */
  data: Prisma.AssetCreateManyInput | Prisma.AssetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Asset update
 */
export type AssetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * The data needed to update a Asset.
   */
  data: Prisma.XOR<Prisma.AssetUpdateInput, Prisma.AssetUncheckedUpdateInput>
  /**
   * Choose, which Asset to update.
   */
  where: Prisma.AssetWhereUniqueInput
}

/**
 * Asset updateMany
 */
export type AssetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Assets.
   */
  data: Prisma.XOR<Prisma.AssetUpdateManyMutationInput, Prisma.AssetUncheckedUpdateManyInput>
  /**
   * Filter which Assets to update
   */
  where?: Prisma.AssetWhereInput
  /**
   * Limit how many Assets to update.
   */
  limit?: number
}

/**
 * Asset updateManyAndReturn
 */
export type AssetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * The data used to update Assets.
   */
  data: Prisma.XOR<Prisma.AssetUpdateManyMutationInput, Prisma.AssetUncheckedUpdateManyInput>
  /**
   * Filter which Assets to update
   */
  where?: Prisma.AssetWhereInput
  /**
   * Limit how many Assets to update.
   */
  limit?: number
}

/**
 * Asset upsert
 */
export type AssetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * The filter to search for the Asset to update in case it exists.
   */
  where: Prisma.AssetWhereUniqueInput
  /**
   * In case the Asset found by the `where` argument doesn't exist, create a new Asset with this data.
   */
  create: Prisma.XOR<Prisma.AssetCreateInput, Prisma.AssetUncheckedCreateInput>
  /**
   * In case the Asset was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssetUpdateInput, Prisma.AssetUncheckedUpdateInput>
}

/**
 * Asset delete
 */
export type AssetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter which Asset to delete.
   */
  where: Prisma.AssetWhereUniqueInput
}

/**
 * Asset deleteMany
 */
export type AssetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Assets to delete
   */
  where?: Prisma.AssetWhereInput
  /**
   * Limit how many Assets to delete.
   */
  limit?: number
}

/**
 * Asset.userAssets
 */
export type Asset$userAssetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserAsset
   */
  select?: Prisma.UserAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserAsset
   */
  omit?: Prisma.UserAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserAssetInclude<ExtArgs> | null
  where?: Prisma.UserAssetWhereInput
  orderBy?: Prisma.UserAssetOrderByWithRelationInput | Prisma.UserAssetOrderByWithRelationInput[]
  cursor?: Prisma.UserAssetWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserAssetScalarFieldEnum | Prisma.UserAssetScalarFieldEnum[]
}

/**
 * Asset.userAssetBalances
 */
export type Asset$userAssetBalancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserAssetBalance
   */
  select?: Prisma.UserAssetBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserAssetBalance
   */
  omit?: Prisma.UserAssetBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserAssetBalanceInclude<ExtArgs> | null
  where?: Prisma.UserAssetBalanceWhereInput
  orderBy?: Prisma.UserAssetBalanceOrderByWithRelationInput | Prisma.UserAssetBalanceOrderByWithRelationInput[]
  cursor?: Prisma.UserAssetBalanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserAssetBalanceScalarFieldEnum | Prisma.UserAssetBalanceScalarFieldEnum[]
}

/**
 * Asset.userStakes
 */
export type Asset$userStakesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  where?: Prisma.UserStakeWhereInput
  orderBy?: Prisma.UserStakeOrderByWithRelationInput | Prisma.UserStakeOrderByWithRelationInput[]
  cursor?: Prisma.UserStakeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserStakeScalarFieldEnum | Prisma.UserStakeScalarFieldEnum[]
}

/**
 * Asset.trades
 */
export type Asset$tradesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trade
   */
  select?: Prisma.TradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trade
   */
  omit?: Prisma.TradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeInclude<ExtArgs> | null
  where?: Prisma.TradeWhereInput
  orderBy?: Prisma.TradeOrderByWithRelationInput | Prisma.TradeOrderByWithRelationInput[]
  cursor?: Prisma.TradeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TradeScalarFieldEnum | Prisma.TradeScalarFieldEnum[]
}

/**
 * Asset.postedTrades
 */
export type Asset$postedTradesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  where?: Prisma.PostedTradeWhereInput
  orderBy?: Prisma.PostedTradeOrderByWithRelationInput | Prisma.PostedTradeOrderByWithRelationInput[]
  cursor?: Prisma.PostedTradeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PostedTradeScalarFieldEnum | Prisma.PostedTradeScalarFieldEnum[]
}

/**
 * Asset.traderTrades
 */
export type Asset$traderTradesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderTrade
   */
  select?: Prisma.TraderTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderTrade
   */
  omit?: Prisma.TraderTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraderTradeInclude<ExtArgs> | null
  where?: Prisma.TraderTradeWhereInput
  orderBy?: Prisma.TraderTradeOrderByWithRelationInput | Prisma.TraderTradeOrderByWithRelationInput[]
  cursor?: Prisma.TraderTradeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TraderTradeScalarFieldEnum | Prisma.TraderTradeScalarFieldEnum[]
}

/**
 * Asset without action
 */
export type AssetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
}
