
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CopiedTrade` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CopiedTrade
 * 
 */
export type CopiedTradeModel = runtime.Types.Result.DefaultSelection<Prisma.$CopiedTradePayload>

export type AggregateCopiedTrade = {
  _count: CopiedTradeCountAggregateOutputType | null
  _min: CopiedTradeMinAggregateOutputType | null
  _max: CopiedTradeMaxAggregateOutputType | null
}

export type CopiedTradeMinAggregateOutputType = {
  id: string | null
  userId: string | null
  traderId: string | null
  tradeId: string | null
  createdAt: Date | null
}

export type CopiedTradeMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  traderId: string | null
  tradeId: string | null
  createdAt: Date | null
}

export type CopiedTradeCountAggregateOutputType = {
  id: number
  userId: number
  traderId: number
  tradeId: number
  createdAt: number
  _all: number
}


export type CopiedTradeMinAggregateInputType = {
  id?: true
  userId?: true
  traderId?: true
  tradeId?: true
  createdAt?: true
}

export type CopiedTradeMaxAggregateInputType = {
  id?: true
  userId?: true
  traderId?: true
  tradeId?: true
  createdAt?: true
}

export type CopiedTradeCountAggregateInputType = {
  id?: true
  userId?: true
  traderId?: true
  tradeId?: true
  createdAt?: true
  _all?: true
}

export type CopiedTradeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CopiedTrade to aggregate.
   */
  where?: Prisma.CopiedTradeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CopiedTrades to fetch.
   */
  orderBy?: Prisma.CopiedTradeOrderByWithRelationInput | Prisma.CopiedTradeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CopiedTradeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CopiedTrades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CopiedTrades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CopiedTrades
  **/
  _count?: true | CopiedTradeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CopiedTradeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CopiedTradeMaxAggregateInputType
}

export type GetCopiedTradeAggregateType<T extends CopiedTradeAggregateArgs> = {
      [P in keyof T & keyof AggregateCopiedTrade]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCopiedTrade[P]>
    : Prisma.GetScalarType<T[P], AggregateCopiedTrade[P]>
}




export type CopiedTradeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CopiedTradeWhereInput
  orderBy?: Prisma.CopiedTradeOrderByWithAggregationInput | Prisma.CopiedTradeOrderByWithAggregationInput[]
  by: Prisma.CopiedTradeScalarFieldEnum[] | Prisma.CopiedTradeScalarFieldEnum
  having?: Prisma.CopiedTradeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CopiedTradeCountAggregateInputType | true
  _min?: CopiedTradeMinAggregateInputType
  _max?: CopiedTradeMaxAggregateInputType
}

export type CopiedTradeGroupByOutputType = {
  id: string
  userId: string
  traderId: string
  tradeId: string | null
  createdAt: Date
  _count: CopiedTradeCountAggregateOutputType | null
  _min: CopiedTradeMinAggregateOutputType | null
  _max: CopiedTradeMaxAggregateOutputType | null
}

type GetCopiedTradeGroupByPayload<T extends CopiedTradeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CopiedTradeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CopiedTradeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CopiedTradeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CopiedTradeGroupByOutputType[P]>
      }
    >
  >



export type CopiedTradeWhereInput = {
  AND?: Prisma.CopiedTradeWhereInput | Prisma.CopiedTradeWhereInput[]
  OR?: Prisma.CopiedTradeWhereInput[]
  NOT?: Prisma.CopiedTradeWhereInput | Prisma.CopiedTradeWhereInput[]
  id?: Prisma.StringFilter<"CopiedTrade"> | string
  userId?: Prisma.StringFilter<"CopiedTrade"> | string
  traderId?: Prisma.StringFilter<"CopiedTrade"> | string
  tradeId?: Prisma.StringNullableFilter<"CopiedTrade"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CopiedTrade"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  trader?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  trade?: Prisma.XOR<Prisma.TraderTradeNullableScalarRelationFilter, Prisma.TraderTradeWhereInput> | null
}

export type CopiedTradeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  traderId?: Prisma.SortOrder
  tradeId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  trader?: Prisma.UserOrderByWithRelationInput
  trade?: Prisma.TraderTradeOrderByWithRelationInput
}

export type CopiedTradeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_traderId?: Prisma.CopiedTradeUserIdTraderIdCompoundUniqueInput
  AND?: Prisma.CopiedTradeWhereInput | Prisma.CopiedTradeWhereInput[]
  OR?: Prisma.CopiedTradeWhereInput[]
  NOT?: Prisma.CopiedTradeWhereInput | Prisma.CopiedTradeWhereInput[]
  userId?: Prisma.StringFilter<"CopiedTrade"> | string
  traderId?: Prisma.StringFilter<"CopiedTrade"> | string
  tradeId?: Prisma.StringNullableFilter<"CopiedTrade"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CopiedTrade"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  trader?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  trade?: Prisma.XOR<Prisma.TraderTradeNullableScalarRelationFilter, Prisma.TraderTradeWhereInput> | null
}, "id" | "userId_traderId">

export type CopiedTradeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  traderId?: Prisma.SortOrder
  tradeId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CopiedTradeCountOrderByAggregateInput
  _max?: Prisma.CopiedTradeMaxOrderByAggregateInput
  _min?: Prisma.CopiedTradeMinOrderByAggregateInput
}

export type CopiedTradeScalarWhereWithAggregatesInput = {
  AND?: Prisma.CopiedTradeScalarWhereWithAggregatesInput | Prisma.CopiedTradeScalarWhereWithAggregatesInput[]
  OR?: Prisma.CopiedTradeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CopiedTradeScalarWhereWithAggregatesInput | Prisma.CopiedTradeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CopiedTrade"> | string
  userId?: Prisma.StringWithAggregatesFilter<"CopiedTrade"> | string
  traderId?: Prisma.StringWithAggregatesFilter<"CopiedTrade"> | string
  tradeId?: Prisma.StringNullableWithAggregatesFilter<"CopiedTrade"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CopiedTrade"> | Date | string
}

export type CopiedTradeCreateInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCopiedTradesInput
  trader: Prisma.UserCreateNestedOneWithoutCopiedTradesAsTraderInput
  trade?: Prisma.TraderTradeCreateNestedOneWithoutCopiedTradesInput
}

export type CopiedTradeUncheckedCreateInput = {
  id?: string
  userId: string
  traderId: string
  tradeId?: string | null
  createdAt?: Date | string
}

export type CopiedTradeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCopiedTradesNestedInput
  trader?: Prisma.UserUpdateOneRequiredWithoutCopiedTradesAsTraderNestedInput
  trade?: Prisma.TraderTradeUpdateOneWithoutCopiedTradesNestedInput
}

export type CopiedTradeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  traderId?: Prisma.StringFieldUpdateOperationsInput | string
  tradeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CopiedTradeCreateManyInput = {
  id?: string
  userId: string
  traderId: string
  tradeId?: string | null
  createdAt?: Date | string
}

export type CopiedTradeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CopiedTradeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  traderId?: Prisma.StringFieldUpdateOperationsInput | string
  tradeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CopiedTradeListRelationFilter = {
  every?: Prisma.CopiedTradeWhereInput
  some?: Prisma.CopiedTradeWhereInput
  none?: Prisma.CopiedTradeWhereInput
}

export type CopiedTradeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CopiedTradeUserIdTraderIdCompoundUniqueInput = {
  userId: string
  traderId: string
}

export type CopiedTradeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  traderId?: Prisma.SortOrder
  tradeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CopiedTradeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  traderId?: Prisma.SortOrder
  tradeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CopiedTradeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  traderId?: Prisma.SortOrder
  tradeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CopiedTradeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutUserInput, Prisma.CopiedTradeUncheckedCreateWithoutUserInput> | Prisma.CopiedTradeCreateWithoutUserInput[] | Prisma.CopiedTradeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutUserInput | Prisma.CopiedTradeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CopiedTradeCreateManyUserInputEnvelope
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
}

export type CopiedTradeCreateNestedManyWithoutTraderInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTraderInput, Prisma.CopiedTradeUncheckedCreateWithoutTraderInput> | Prisma.CopiedTradeCreateWithoutTraderInput[] | Prisma.CopiedTradeUncheckedCreateWithoutTraderInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutTraderInput | Prisma.CopiedTradeCreateOrConnectWithoutTraderInput[]
  createMany?: Prisma.CopiedTradeCreateManyTraderInputEnvelope
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
}

export type CopiedTradeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutUserInput, Prisma.CopiedTradeUncheckedCreateWithoutUserInput> | Prisma.CopiedTradeCreateWithoutUserInput[] | Prisma.CopiedTradeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutUserInput | Prisma.CopiedTradeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CopiedTradeCreateManyUserInputEnvelope
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
}

export type CopiedTradeUncheckedCreateNestedManyWithoutTraderInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTraderInput, Prisma.CopiedTradeUncheckedCreateWithoutTraderInput> | Prisma.CopiedTradeCreateWithoutTraderInput[] | Prisma.CopiedTradeUncheckedCreateWithoutTraderInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutTraderInput | Prisma.CopiedTradeCreateOrConnectWithoutTraderInput[]
  createMany?: Prisma.CopiedTradeCreateManyTraderInputEnvelope
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
}

export type CopiedTradeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutUserInput, Prisma.CopiedTradeUncheckedCreateWithoutUserInput> | Prisma.CopiedTradeCreateWithoutUserInput[] | Prisma.CopiedTradeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutUserInput | Prisma.CopiedTradeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CopiedTradeUpsertWithWhereUniqueWithoutUserInput | Prisma.CopiedTradeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CopiedTradeCreateManyUserInputEnvelope
  set?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  disconnect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  delete?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  update?: Prisma.CopiedTradeUpdateWithWhereUniqueWithoutUserInput | Prisma.CopiedTradeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CopiedTradeUpdateManyWithWhereWithoutUserInput | Prisma.CopiedTradeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CopiedTradeScalarWhereInput | Prisma.CopiedTradeScalarWhereInput[]
}

export type CopiedTradeUpdateManyWithoutTraderNestedInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTraderInput, Prisma.CopiedTradeUncheckedCreateWithoutTraderInput> | Prisma.CopiedTradeCreateWithoutTraderInput[] | Prisma.CopiedTradeUncheckedCreateWithoutTraderInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutTraderInput | Prisma.CopiedTradeCreateOrConnectWithoutTraderInput[]
  upsert?: Prisma.CopiedTradeUpsertWithWhereUniqueWithoutTraderInput | Prisma.CopiedTradeUpsertWithWhereUniqueWithoutTraderInput[]
  createMany?: Prisma.CopiedTradeCreateManyTraderInputEnvelope
  set?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  disconnect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  delete?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  update?: Prisma.CopiedTradeUpdateWithWhereUniqueWithoutTraderInput | Prisma.CopiedTradeUpdateWithWhereUniqueWithoutTraderInput[]
  updateMany?: Prisma.CopiedTradeUpdateManyWithWhereWithoutTraderInput | Prisma.CopiedTradeUpdateManyWithWhereWithoutTraderInput[]
  deleteMany?: Prisma.CopiedTradeScalarWhereInput | Prisma.CopiedTradeScalarWhereInput[]
}

export type CopiedTradeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutUserInput, Prisma.CopiedTradeUncheckedCreateWithoutUserInput> | Prisma.CopiedTradeCreateWithoutUserInput[] | Prisma.CopiedTradeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutUserInput | Prisma.CopiedTradeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CopiedTradeUpsertWithWhereUniqueWithoutUserInput | Prisma.CopiedTradeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CopiedTradeCreateManyUserInputEnvelope
  set?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  disconnect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  delete?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  update?: Prisma.CopiedTradeUpdateWithWhereUniqueWithoutUserInput | Prisma.CopiedTradeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CopiedTradeUpdateManyWithWhereWithoutUserInput | Prisma.CopiedTradeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CopiedTradeScalarWhereInput | Prisma.CopiedTradeScalarWhereInput[]
}

export type CopiedTradeUncheckedUpdateManyWithoutTraderNestedInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTraderInput, Prisma.CopiedTradeUncheckedCreateWithoutTraderInput> | Prisma.CopiedTradeCreateWithoutTraderInput[] | Prisma.CopiedTradeUncheckedCreateWithoutTraderInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutTraderInput | Prisma.CopiedTradeCreateOrConnectWithoutTraderInput[]
  upsert?: Prisma.CopiedTradeUpsertWithWhereUniqueWithoutTraderInput | Prisma.CopiedTradeUpsertWithWhereUniqueWithoutTraderInput[]
  createMany?: Prisma.CopiedTradeCreateManyTraderInputEnvelope
  set?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  disconnect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  delete?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  update?: Prisma.CopiedTradeUpdateWithWhereUniqueWithoutTraderInput | Prisma.CopiedTradeUpdateWithWhereUniqueWithoutTraderInput[]
  updateMany?: Prisma.CopiedTradeUpdateManyWithWhereWithoutTraderInput | Prisma.CopiedTradeUpdateManyWithWhereWithoutTraderInput[]
  deleteMany?: Prisma.CopiedTradeScalarWhereInput | Prisma.CopiedTradeScalarWhereInput[]
}

export type CopiedTradeCreateNestedManyWithoutTradeInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTradeInput, Prisma.CopiedTradeUncheckedCreateWithoutTradeInput> | Prisma.CopiedTradeCreateWithoutTradeInput[] | Prisma.CopiedTradeUncheckedCreateWithoutTradeInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutTradeInput | Prisma.CopiedTradeCreateOrConnectWithoutTradeInput[]
  createMany?: Prisma.CopiedTradeCreateManyTradeInputEnvelope
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
}

export type CopiedTradeUncheckedCreateNestedManyWithoutTradeInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTradeInput, Prisma.CopiedTradeUncheckedCreateWithoutTradeInput> | Prisma.CopiedTradeCreateWithoutTradeInput[] | Prisma.CopiedTradeUncheckedCreateWithoutTradeInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutTradeInput | Prisma.CopiedTradeCreateOrConnectWithoutTradeInput[]
  createMany?: Prisma.CopiedTradeCreateManyTradeInputEnvelope
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
}

export type CopiedTradeUpdateManyWithoutTradeNestedInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTradeInput, Prisma.CopiedTradeUncheckedCreateWithoutTradeInput> | Prisma.CopiedTradeCreateWithoutTradeInput[] | Prisma.CopiedTradeUncheckedCreateWithoutTradeInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutTradeInput | Prisma.CopiedTradeCreateOrConnectWithoutTradeInput[]
  upsert?: Prisma.CopiedTradeUpsertWithWhereUniqueWithoutTradeInput | Prisma.CopiedTradeUpsertWithWhereUniqueWithoutTradeInput[]
  createMany?: Prisma.CopiedTradeCreateManyTradeInputEnvelope
  set?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  disconnect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  delete?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  update?: Prisma.CopiedTradeUpdateWithWhereUniqueWithoutTradeInput | Prisma.CopiedTradeUpdateWithWhereUniqueWithoutTradeInput[]
  updateMany?: Prisma.CopiedTradeUpdateManyWithWhereWithoutTradeInput | Prisma.CopiedTradeUpdateManyWithWhereWithoutTradeInput[]
  deleteMany?: Prisma.CopiedTradeScalarWhereInput | Prisma.CopiedTradeScalarWhereInput[]
}

export type CopiedTradeUncheckedUpdateManyWithoutTradeNestedInput = {
  create?: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTradeInput, Prisma.CopiedTradeUncheckedCreateWithoutTradeInput> | Prisma.CopiedTradeCreateWithoutTradeInput[] | Prisma.CopiedTradeUncheckedCreateWithoutTradeInput[]
  connectOrCreate?: Prisma.CopiedTradeCreateOrConnectWithoutTradeInput | Prisma.CopiedTradeCreateOrConnectWithoutTradeInput[]
  upsert?: Prisma.CopiedTradeUpsertWithWhereUniqueWithoutTradeInput | Prisma.CopiedTradeUpsertWithWhereUniqueWithoutTradeInput[]
  createMany?: Prisma.CopiedTradeCreateManyTradeInputEnvelope
  set?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  disconnect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  delete?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  connect?: Prisma.CopiedTradeWhereUniqueInput | Prisma.CopiedTradeWhereUniqueInput[]
  update?: Prisma.CopiedTradeUpdateWithWhereUniqueWithoutTradeInput | Prisma.CopiedTradeUpdateWithWhereUniqueWithoutTradeInput[]
  updateMany?: Prisma.CopiedTradeUpdateManyWithWhereWithoutTradeInput | Prisma.CopiedTradeUpdateManyWithWhereWithoutTradeInput[]
  deleteMany?: Prisma.CopiedTradeScalarWhereInput | Prisma.CopiedTradeScalarWhereInput[]
}

export type CopiedTradeCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  trader: Prisma.UserCreateNestedOneWithoutCopiedTradesAsTraderInput
  trade?: Prisma.TraderTradeCreateNestedOneWithoutCopiedTradesInput
}

export type CopiedTradeUncheckedCreateWithoutUserInput = {
  id?: string
  traderId: string
  tradeId?: string | null
  createdAt?: Date | string
}

export type CopiedTradeCreateOrConnectWithoutUserInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  create: Prisma.XOR<Prisma.CopiedTradeCreateWithoutUserInput, Prisma.CopiedTradeUncheckedCreateWithoutUserInput>
}

export type CopiedTradeCreateManyUserInputEnvelope = {
  data: Prisma.CopiedTradeCreateManyUserInput | Prisma.CopiedTradeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type CopiedTradeCreateWithoutTraderInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCopiedTradesInput
  trade?: Prisma.TraderTradeCreateNestedOneWithoutCopiedTradesInput
}

export type CopiedTradeUncheckedCreateWithoutTraderInput = {
  id?: string
  userId: string
  tradeId?: string | null
  createdAt?: Date | string
}

export type CopiedTradeCreateOrConnectWithoutTraderInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  create: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTraderInput, Prisma.CopiedTradeUncheckedCreateWithoutTraderInput>
}

export type CopiedTradeCreateManyTraderInputEnvelope = {
  data: Prisma.CopiedTradeCreateManyTraderInput | Prisma.CopiedTradeCreateManyTraderInput[]
  skipDuplicates?: boolean
}

export type CopiedTradeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  update: Prisma.XOR<Prisma.CopiedTradeUpdateWithoutUserInput, Prisma.CopiedTradeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CopiedTradeCreateWithoutUserInput, Prisma.CopiedTradeUncheckedCreateWithoutUserInput>
}

export type CopiedTradeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  data: Prisma.XOR<Prisma.CopiedTradeUpdateWithoutUserInput, Prisma.CopiedTradeUncheckedUpdateWithoutUserInput>
}

export type CopiedTradeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CopiedTradeScalarWhereInput
  data: Prisma.XOR<Prisma.CopiedTradeUpdateManyMutationInput, Prisma.CopiedTradeUncheckedUpdateManyWithoutUserInput>
}

export type CopiedTradeScalarWhereInput = {
  AND?: Prisma.CopiedTradeScalarWhereInput | Prisma.CopiedTradeScalarWhereInput[]
  OR?: Prisma.CopiedTradeScalarWhereInput[]
  NOT?: Prisma.CopiedTradeScalarWhereInput | Prisma.CopiedTradeScalarWhereInput[]
  id?: Prisma.StringFilter<"CopiedTrade"> | string
  userId?: Prisma.StringFilter<"CopiedTrade"> | string
  traderId?: Prisma.StringFilter<"CopiedTrade"> | string
  tradeId?: Prisma.StringNullableFilter<"CopiedTrade"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CopiedTrade"> | Date | string
}

export type CopiedTradeUpsertWithWhereUniqueWithoutTraderInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  update: Prisma.XOR<Prisma.CopiedTradeUpdateWithoutTraderInput, Prisma.CopiedTradeUncheckedUpdateWithoutTraderInput>
  create: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTraderInput, Prisma.CopiedTradeUncheckedCreateWithoutTraderInput>
}

export type CopiedTradeUpdateWithWhereUniqueWithoutTraderInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  data: Prisma.XOR<Prisma.CopiedTradeUpdateWithoutTraderInput, Prisma.CopiedTradeUncheckedUpdateWithoutTraderInput>
}

export type CopiedTradeUpdateManyWithWhereWithoutTraderInput = {
  where: Prisma.CopiedTradeScalarWhereInput
  data: Prisma.XOR<Prisma.CopiedTradeUpdateManyMutationInput, Prisma.CopiedTradeUncheckedUpdateManyWithoutTraderInput>
}

export type CopiedTradeCreateWithoutTradeInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCopiedTradesInput
  trader: Prisma.UserCreateNestedOneWithoutCopiedTradesAsTraderInput
}

export type CopiedTradeUncheckedCreateWithoutTradeInput = {
  id?: string
  userId: string
  traderId: string
  createdAt?: Date | string
}

export type CopiedTradeCreateOrConnectWithoutTradeInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  create: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTradeInput, Prisma.CopiedTradeUncheckedCreateWithoutTradeInput>
}

export type CopiedTradeCreateManyTradeInputEnvelope = {
  data: Prisma.CopiedTradeCreateManyTradeInput | Prisma.CopiedTradeCreateManyTradeInput[]
  skipDuplicates?: boolean
}

export type CopiedTradeUpsertWithWhereUniqueWithoutTradeInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  update: Prisma.XOR<Prisma.CopiedTradeUpdateWithoutTradeInput, Prisma.CopiedTradeUncheckedUpdateWithoutTradeInput>
  create: Prisma.XOR<Prisma.CopiedTradeCreateWithoutTradeInput, Prisma.CopiedTradeUncheckedCreateWithoutTradeInput>
}

export type CopiedTradeUpdateWithWhereUniqueWithoutTradeInput = {
  where: Prisma.CopiedTradeWhereUniqueInput
  data: Prisma.XOR<Prisma.CopiedTradeUpdateWithoutTradeInput, Prisma.CopiedTradeUncheckedUpdateWithoutTradeInput>
}

export type CopiedTradeUpdateManyWithWhereWithoutTradeInput = {
  where: Prisma.CopiedTradeScalarWhereInput
  data: Prisma.XOR<Prisma.CopiedTradeUpdateManyMutationInput, Prisma.CopiedTradeUncheckedUpdateManyWithoutTradeInput>
}

export type CopiedTradeCreateManyUserInput = {
  id?: string
  traderId: string
  tradeId?: string | null
  createdAt?: Date | string
}

export type CopiedTradeCreateManyTraderInput = {
  id?: string
  userId: string
  tradeId?: string | null
  createdAt?: Date | string
}

export type CopiedTradeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trader?: Prisma.UserUpdateOneRequiredWithoutCopiedTradesAsTraderNestedInput
  trade?: Prisma.TraderTradeUpdateOneWithoutCopiedTradesNestedInput
}

export type CopiedTradeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  traderId?: Prisma.StringFieldUpdateOperationsInput | string
  tradeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CopiedTradeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  traderId?: Prisma.StringFieldUpdateOperationsInput | string
  tradeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CopiedTradeUpdateWithoutTraderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCopiedTradesNestedInput
  trade?: Prisma.TraderTradeUpdateOneWithoutCopiedTradesNestedInput
}

export type CopiedTradeUncheckedUpdateWithoutTraderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  tradeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CopiedTradeUncheckedUpdateManyWithoutTraderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  tradeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CopiedTradeCreateManyTradeInput = {
  id?: string
  userId: string
  traderId: string
  createdAt?: Date | string
}

export type CopiedTradeUpdateWithoutTradeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCopiedTradesNestedInput
  trader?: Prisma.UserUpdateOneRequiredWithoutCopiedTradesAsTraderNestedInput
}

export type CopiedTradeUncheckedUpdateWithoutTradeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  traderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CopiedTradeUncheckedUpdateManyWithoutTradeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  traderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CopiedTradeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  traderId?: boolean
  tradeId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trade?: boolean | Prisma.CopiedTrade$tradeArgs<ExtArgs>
}, ExtArgs["result"]["copiedTrade"]>

export type CopiedTradeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  traderId?: boolean
  tradeId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trade?: boolean | Prisma.CopiedTrade$tradeArgs<ExtArgs>
}, ExtArgs["result"]["copiedTrade"]>

export type CopiedTradeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  traderId?: boolean
  tradeId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trade?: boolean | Prisma.CopiedTrade$tradeArgs<ExtArgs>
}, ExtArgs["result"]["copiedTrade"]>

export type CopiedTradeSelectScalar = {
  id?: boolean
  userId?: boolean
  traderId?: boolean
  tradeId?: boolean
  createdAt?: boolean
}

export type CopiedTradeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "traderId" | "tradeId" | "createdAt", ExtArgs["result"]["copiedTrade"]>
export type CopiedTradeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trade?: boolean | Prisma.CopiedTrade$tradeArgs<ExtArgs>
}
export type CopiedTradeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trade?: boolean | Prisma.CopiedTrade$tradeArgs<ExtArgs>
}
export type CopiedTradeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trader?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  trade?: boolean | Prisma.CopiedTrade$tradeArgs<ExtArgs>
}

export type $CopiedTradePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CopiedTrade"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    trader: Prisma.$UserPayload<ExtArgs>
    trade: Prisma.$TraderTradePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    traderId: string
    tradeId: string | null
    createdAt: Date
  }, ExtArgs["result"]["copiedTrade"]>
  composites: {}
}

export type CopiedTradeGetPayload<S extends boolean | null | undefined | CopiedTradeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload, S>

export type CopiedTradeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CopiedTradeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CopiedTradeCountAggregateInputType | true
  }

export interface CopiedTradeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CopiedTrade'], meta: { name: 'CopiedTrade' } }
  /**
   * Find zero or one CopiedTrade that matches the filter.
   * @param {CopiedTradeFindUniqueArgs} args - Arguments to find a CopiedTrade
   * @example
   * // Get one CopiedTrade
   * const copiedTrade = await prisma.copiedTrade.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CopiedTradeFindUniqueArgs>(args: Prisma.SelectSubset<T, CopiedTradeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CopiedTradeClient<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CopiedTrade that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CopiedTradeFindUniqueOrThrowArgs} args - Arguments to find a CopiedTrade
   * @example
   * // Get one CopiedTrade
   * const copiedTrade = await prisma.copiedTrade.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CopiedTradeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CopiedTradeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CopiedTradeClient<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CopiedTrade that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CopiedTradeFindFirstArgs} args - Arguments to find a CopiedTrade
   * @example
   * // Get one CopiedTrade
   * const copiedTrade = await prisma.copiedTrade.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CopiedTradeFindFirstArgs>(args?: Prisma.SelectSubset<T, CopiedTradeFindFirstArgs<ExtArgs>>): Prisma.Prisma__CopiedTradeClient<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CopiedTrade that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CopiedTradeFindFirstOrThrowArgs} args - Arguments to find a CopiedTrade
   * @example
   * // Get one CopiedTrade
   * const copiedTrade = await prisma.copiedTrade.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CopiedTradeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CopiedTradeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CopiedTradeClient<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CopiedTrades that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CopiedTradeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CopiedTrades
   * const copiedTrades = await prisma.copiedTrade.findMany()
   * 
   * // Get first 10 CopiedTrades
   * const copiedTrades = await prisma.copiedTrade.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const copiedTradeWithIdOnly = await prisma.copiedTrade.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CopiedTradeFindManyArgs>(args?: Prisma.SelectSubset<T, CopiedTradeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CopiedTrade.
   * @param {CopiedTradeCreateArgs} args - Arguments to create a CopiedTrade.
   * @example
   * // Create one CopiedTrade
   * const CopiedTrade = await prisma.copiedTrade.create({
   *   data: {
   *     // ... data to create a CopiedTrade
   *   }
   * })
   * 
   */
  create<T extends CopiedTradeCreateArgs>(args: Prisma.SelectSubset<T, CopiedTradeCreateArgs<ExtArgs>>): Prisma.Prisma__CopiedTradeClient<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CopiedTrades.
   * @param {CopiedTradeCreateManyArgs} args - Arguments to create many CopiedTrades.
   * @example
   * // Create many CopiedTrades
   * const copiedTrade = await prisma.copiedTrade.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CopiedTradeCreateManyArgs>(args?: Prisma.SelectSubset<T, CopiedTradeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CopiedTrades and returns the data saved in the database.
   * @param {CopiedTradeCreateManyAndReturnArgs} args - Arguments to create many CopiedTrades.
   * @example
   * // Create many CopiedTrades
   * const copiedTrade = await prisma.copiedTrade.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CopiedTrades and only return the `id`
   * const copiedTradeWithIdOnly = await prisma.copiedTrade.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CopiedTradeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CopiedTradeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CopiedTrade.
   * @param {CopiedTradeDeleteArgs} args - Arguments to delete one CopiedTrade.
   * @example
   * // Delete one CopiedTrade
   * const CopiedTrade = await prisma.copiedTrade.delete({
   *   where: {
   *     // ... filter to delete one CopiedTrade
   *   }
   * })
   * 
   */
  delete<T extends CopiedTradeDeleteArgs>(args: Prisma.SelectSubset<T, CopiedTradeDeleteArgs<ExtArgs>>): Prisma.Prisma__CopiedTradeClient<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CopiedTrade.
   * @param {CopiedTradeUpdateArgs} args - Arguments to update one CopiedTrade.
   * @example
   * // Update one CopiedTrade
   * const copiedTrade = await prisma.copiedTrade.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CopiedTradeUpdateArgs>(args: Prisma.SelectSubset<T, CopiedTradeUpdateArgs<ExtArgs>>): Prisma.Prisma__CopiedTradeClient<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CopiedTrades.
   * @param {CopiedTradeDeleteManyArgs} args - Arguments to filter CopiedTrades to delete.
   * @example
   * // Delete a few CopiedTrades
   * const { count } = await prisma.copiedTrade.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CopiedTradeDeleteManyArgs>(args?: Prisma.SelectSubset<T, CopiedTradeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CopiedTrades.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CopiedTradeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CopiedTrades
   * const copiedTrade = await prisma.copiedTrade.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CopiedTradeUpdateManyArgs>(args: Prisma.SelectSubset<T, CopiedTradeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CopiedTrades and returns the data updated in the database.
   * @param {CopiedTradeUpdateManyAndReturnArgs} args - Arguments to update many CopiedTrades.
   * @example
   * // Update many CopiedTrades
   * const copiedTrade = await prisma.copiedTrade.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CopiedTrades and only return the `id`
   * const copiedTradeWithIdOnly = await prisma.copiedTrade.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CopiedTradeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CopiedTradeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CopiedTrade.
   * @param {CopiedTradeUpsertArgs} args - Arguments to update or create a CopiedTrade.
   * @example
   * // Update or create a CopiedTrade
   * const copiedTrade = await prisma.copiedTrade.upsert({
   *   create: {
   *     // ... data to create a CopiedTrade
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CopiedTrade we want to update
   *   }
   * })
   */
  upsert<T extends CopiedTradeUpsertArgs>(args: Prisma.SelectSubset<T, CopiedTradeUpsertArgs<ExtArgs>>): Prisma.Prisma__CopiedTradeClient<runtime.Types.Result.GetResult<Prisma.$CopiedTradePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CopiedTrades.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CopiedTradeCountArgs} args - Arguments to filter CopiedTrades to count.
   * @example
   * // Count the number of CopiedTrades
   * const count = await prisma.copiedTrade.count({
   *   where: {
   *     // ... the filter for the CopiedTrades we want to count
   *   }
   * })
  **/
  count<T extends CopiedTradeCountArgs>(
    args?: Prisma.Subset<T, CopiedTradeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CopiedTradeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CopiedTrade.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CopiedTradeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CopiedTradeAggregateArgs>(args: Prisma.Subset<T, CopiedTradeAggregateArgs>): Prisma.PrismaPromise<GetCopiedTradeAggregateType<T>>

  /**
   * Group by CopiedTrade.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CopiedTradeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CopiedTradeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CopiedTradeGroupByArgs['orderBy'] }
      : { orderBy?: CopiedTradeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CopiedTradeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCopiedTradeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CopiedTrade model
 */
readonly fields: CopiedTradeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CopiedTrade.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CopiedTradeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  trader<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  trade<T extends Prisma.CopiedTrade$tradeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CopiedTrade$tradeArgs<ExtArgs>>): Prisma.Prisma__TraderTradeClient<runtime.Types.Result.GetResult<Prisma.$TraderTradePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CopiedTrade model
 */
export interface CopiedTradeFieldRefs {
  readonly id: Prisma.FieldRef<"CopiedTrade", 'String'>
  readonly userId: Prisma.FieldRef<"CopiedTrade", 'String'>
  readonly traderId: Prisma.FieldRef<"CopiedTrade", 'String'>
  readonly tradeId: Prisma.FieldRef<"CopiedTrade", 'String'>
  readonly createdAt: Prisma.FieldRef<"CopiedTrade", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CopiedTrade findUnique
 */
export type CopiedTradeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * Filter, which CopiedTrade to fetch.
   */
  where: Prisma.CopiedTradeWhereUniqueInput
}

/**
 * CopiedTrade findUniqueOrThrow
 */
export type CopiedTradeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * Filter, which CopiedTrade to fetch.
   */
  where: Prisma.CopiedTradeWhereUniqueInput
}

/**
 * CopiedTrade findFirst
 */
export type CopiedTradeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * Filter, which CopiedTrade to fetch.
   */
  where?: Prisma.CopiedTradeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CopiedTrades to fetch.
   */
  orderBy?: Prisma.CopiedTradeOrderByWithRelationInput | Prisma.CopiedTradeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CopiedTrades.
   */
  cursor?: Prisma.CopiedTradeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CopiedTrades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CopiedTrades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CopiedTrades.
   */
  distinct?: Prisma.CopiedTradeScalarFieldEnum | Prisma.CopiedTradeScalarFieldEnum[]
}

/**
 * CopiedTrade findFirstOrThrow
 */
export type CopiedTradeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * Filter, which CopiedTrade to fetch.
   */
  where?: Prisma.CopiedTradeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CopiedTrades to fetch.
   */
  orderBy?: Prisma.CopiedTradeOrderByWithRelationInput | Prisma.CopiedTradeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CopiedTrades.
   */
  cursor?: Prisma.CopiedTradeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CopiedTrades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CopiedTrades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CopiedTrades.
   */
  distinct?: Prisma.CopiedTradeScalarFieldEnum | Prisma.CopiedTradeScalarFieldEnum[]
}

/**
 * CopiedTrade findMany
 */
export type CopiedTradeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * Filter, which CopiedTrades to fetch.
   */
  where?: Prisma.CopiedTradeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CopiedTrades to fetch.
   */
  orderBy?: Prisma.CopiedTradeOrderByWithRelationInput | Prisma.CopiedTradeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CopiedTrades.
   */
  cursor?: Prisma.CopiedTradeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CopiedTrades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CopiedTrades.
   */
  skip?: number
  distinct?: Prisma.CopiedTradeScalarFieldEnum | Prisma.CopiedTradeScalarFieldEnum[]
}

/**
 * CopiedTrade create
 */
export type CopiedTradeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * The data needed to create a CopiedTrade.
   */
  data: Prisma.XOR<Prisma.CopiedTradeCreateInput, Prisma.CopiedTradeUncheckedCreateInput>
}

/**
 * CopiedTrade createMany
 */
export type CopiedTradeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CopiedTrades.
   */
  data: Prisma.CopiedTradeCreateManyInput | Prisma.CopiedTradeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CopiedTrade createManyAndReturn
 */
export type CopiedTradeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * The data used to create many CopiedTrades.
   */
  data: Prisma.CopiedTradeCreateManyInput | Prisma.CopiedTradeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CopiedTrade update
 */
export type CopiedTradeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * The data needed to update a CopiedTrade.
   */
  data: Prisma.XOR<Prisma.CopiedTradeUpdateInput, Prisma.CopiedTradeUncheckedUpdateInput>
  /**
   * Choose, which CopiedTrade to update.
   */
  where: Prisma.CopiedTradeWhereUniqueInput
}

/**
 * CopiedTrade updateMany
 */
export type CopiedTradeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CopiedTrades.
   */
  data: Prisma.XOR<Prisma.CopiedTradeUpdateManyMutationInput, Prisma.CopiedTradeUncheckedUpdateManyInput>
  /**
   * Filter which CopiedTrades to update
   */
  where?: Prisma.CopiedTradeWhereInput
  /**
   * Limit how many CopiedTrades to update.
   */
  limit?: number
}

/**
 * CopiedTrade updateManyAndReturn
 */
export type CopiedTradeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * The data used to update CopiedTrades.
   */
  data: Prisma.XOR<Prisma.CopiedTradeUpdateManyMutationInput, Prisma.CopiedTradeUncheckedUpdateManyInput>
  /**
   * Filter which CopiedTrades to update
   */
  where?: Prisma.CopiedTradeWhereInput
  /**
   * Limit how many CopiedTrades to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CopiedTrade upsert
 */
export type CopiedTradeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * The filter to search for the CopiedTrade to update in case it exists.
   */
  where: Prisma.CopiedTradeWhereUniqueInput
  /**
   * In case the CopiedTrade found by the `where` argument doesn't exist, create a new CopiedTrade with this data.
   */
  create: Prisma.XOR<Prisma.CopiedTradeCreateInput, Prisma.CopiedTradeUncheckedCreateInput>
  /**
   * In case the CopiedTrade was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CopiedTradeUpdateInput, Prisma.CopiedTradeUncheckedUpdateInput>
}

/**
 * CopiedTrade delete
 */
export type CopiedTradeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
  /**
   * Filter which CopiedTrade to delete.
   */
  where: Prisma.CopiedTradeWhereUniqueInput
}

/**
 * CopiedTrade deleteMany
 */
export type CopiedTradeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CopiedTrades to delete
   */
  where?: Prisma.CopiedTradeWhereInput
  /**
   * Limit how many CopiedTrades to delete.
   */
  limit?: number
}

/**
 * CopiedTrade.trade
 */
export type CopiedTrade$tradeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderTrade
   */
  select?: Prisma.TraderTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderTrade
   */
  omit?: Prisma.TraderTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraderTradeInclude<ExtArgs> | null
  where?: Prisma.TraderTradeWhereInput
}

/**
 * CopiedTrade without action
 */
export type CopiedTradeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CopiedTrade
   */
  select?: Prisma.CopiedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CopiedTrade
   */
  omit?: Prisma.CopiedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CopiedTradeInclude<ExtArgs> | null
}
