
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DepositMethod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DepositMethod
 * 
 */
export type DepositMethodModel = runtime.Types.Result.DefaultSelection<Prisma.$DepositMethodPayload>

export type AggregateDepositMethod = {
  _count: DepositMethodCountAggregateOutputType | null
  _min: DepositMethodMinAggregateOutputType | null
  _max: DepositMethodMaxAggregateOutputType | null
}

export type DepositMethodMinAggregateOutputType = {
  id: string | null
  name: string | null
  enabled: boolean | null
  description: string | null
  cryptoType: string | null
  network: string | null
  networkName: string | null
  address: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DepositMethodMaxAggregateOutputType = {
  id: string | null
  name: string | null
  enabled: boolean | null
  description: string | null
  cryptoType: string | null
  network: string | null
  networkName: string | null
  address: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DepositMethodCountAggregateOutputType = {
  id: number
  name: number
  enabled: number
  description: number
  cryptoType: number
  network: number
  networkName: number
  address: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DepositMethodMinAggregateInputType = {
  id?: true
  name?: true
  enabled?: true
  description?: true
  cryptoType?: true
  network?: true
  networkName?: true
  address?: true
  createdAt?: true
  updatedAt?: true
}

export type DepositMethodMaxAggregateInputType = {
  id?: true
  name?: true
  enabled?: true
  description?: true
  cryptoType?: true
  network?: true
  networkName?: true
  address?: true
  createdAt?: true
  updatedAt?: true
}

export type DepositMethodCountAggregateInputType = {
  id?: true
  name?: true
  enabled?: true
  description?: true
  cryptoType?: true
  network?: true
  networkName?: true
  address?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DepositMethodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DepositMethod to aggregate.
   */
  where?: Prisma.DepositMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DepositMethods to fetch.
   */
  orderBy?: Prisma.DepositMethodOrderByWithRelationInput | Prisma.DepositMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DepositMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DepositMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DepositMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DepositMethods
  **/
  _count?: true | DepositMethodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DepositMethodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DepositMethodMaxAggregateInputType
}

export type GetDepositMethodAggregateType<T extends DepositMethodAggregateArgs> = {
      [P in keyof T & keyof AggregateDepositMethod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDepositMethod[P]>
    : Prisma.GetScalarType<T[P], AggregateDepositMethod[P]>
}




export type DepositMethodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DepositMethodWhereInput
  orderBy?: Prisma.DepositMethodOrderByWithAggregationInput | Prisma.DepositMethodOrderByWithAggregationInput[]
  by: Prisma.DepositMethodScalarFieldEnum[] | Prisma.DepositMethodScalarFieldEnum
  having?: Prisma.DepositMethodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DepositMethodCountAggregateInputType | true
  _min?: DepositMethodMinAggregateInputType
  _max?: DepositMethodMaxAggregateInputType
}

export type DepositMethodGroupByOutputType = {
  id: string
  name: string
  enabled: boolean
  description: string | null
  cryptoType: string | null
  network: string | null
  networkName: string | null
  address: string | null
  createdAt: Date
  updatedAt: Date
  _count: DepositMethodCountAggregateOutputType | null
  _min: DepositMethodMinAggregateOutputType | null
  _max: DepositMethodMaxAggregateOutputType | null
}

type GetDepositMethodGroupByPayload<T extends DepositMethodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DepositMethodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DepositMethodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DepositMethodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DepositMethodGroupByOutputType[P]>
      }
    >
  >



export type DepositMethodWhereInput = {
  AND?: Prisma.DepositMethodWhereInput | Prisma.DepositMethodWhereInput[]
  OR?: Prisma.DepositMethodWhereInput[]
  NOT?: Prisma.DepositMethodWhereInput | Prisma.DepositMethodWhereInput[]
  id?: Prisma.StringFilter<"DepositMethod"> | string
  name?: Prisma.StringFilter<"DepositMethod"> | string
  enabled?: Prisma.BoolFilter<"DepositMethod"> | boolean
  description?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  cryptoType?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  network?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  networkName?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  address?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DepositMethod"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DepositMethod"> | Date | string
}

export type DepositMethodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  cryptoType?: Prisma.SortOrderInput | Prisma.SortOrder
  network?: Prisma.SortOrderInput | Prisma.SortOrder
  networkName?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DepositMethodWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.DepositMethodWhereInput | Prisma.DepositMethodWhereInput[]
  OR?: Prisma.DepositMethodWhereInput[]
  NOT?: Prisma.DepositMethodWhereInput | Prisma.DepositMethodWhereInput[]
  enabled?: Prisma.BoolFilter<"DepositMethod"> | boolean
  description?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  cryptoType?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  network?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  networkName?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  address?: Prisma.StringNullableFilter<"DepositMethod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DepositMethod"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DepositMethod"> | Date | string
}, "id" | "name">

export type DepositMethodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  cryptoType?: Prisma.SortOrderInput | Prisma.SortOrder
  network?: Prisma.SortOrderInput | Prisma.SortOrder
  networkName?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DepositMethodCountOrderByAggregateInput
  _max?: Prisma.DepositMethodMaxOrderByAggregateInput
  _min?: Prisma.DepositMethodMinOrderByAggregateInput
}

export type DepositMethodScalarWhereWithAggregatesInput = {
  AND?: Prisma.DepositMethodScalarWhereWithAggregatesInput | Prisma.DepositMethodScalarWhereWithAggregatesInput[]
  OR?: Prisma.DepositMethodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DepositMethodScalarWhereWithAggregatesInput | Prisma.DepositMethodScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DepositMethod"> | string
  name?: Prisma.StringWithAggregatesFilter<"DepositMethod"> | string
  enabled?: Prisma.BoolWithAggregatesFilter<"DepositMethod"> | boolean
  description?: Prisma.StringNullableWithAggregatesFilter<"DepositMethod"> | string | null
  cryptoType?: Prisma.StringNullableWithAggregatesFilter<"DepositMethod"> | string | null
  network?: Prisma.StringNullableWithAggregatesFilter<"DepositMethod"> | string | null
  networkName?: Prisma.StringNullableWithAggregatesFilter<"DepositMethod"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"DepositMethod"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DepositMethod"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DepositMethod"> | Date | string
}

export type DepositMethodCreateInput = {
  id?: string
  name: string
  enabled?: boolean
  description?: string | null
  cryptoType?: string | null
  network?: string | null
  networkName?: string | null
  address?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DepositMethodUncheckedCreateInput = {
  id?: string
  name: string
  enabled?: boolean
  description?: string | null
  cryptoType?: string | null
  network?: string | null
  networkName?: string | null
  address?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DepositMethodUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cryptoType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  network?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  networkName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DepositMethodUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cryptoType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  network?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  networkName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DepositMethodCreateManyInput = {
  id?: string
  name: string
  enabled?: boolean
  description?: string | null
  cryptoType?: string | null
  network?: string | null
  networkName?: string | null
  address?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DepositMethodUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cryptoType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  network?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  networkName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DepositMethodUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cryptoType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  network?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  networkName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DepositMethodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cryptoType?: Prisma.SortOrder
  network?: Prisma.SortOrder
  networkName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DepositMethodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cryptoType?: Prisma.SortOrder
  network?: Prisma.SortOrder
  networkName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DepositMethodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cryptoType?: Prisma.SortOrder
  network?: Prisma.SortOrder
  networkName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type DepositMethodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  enabled?: boolean
  description?: boolean
  cryptoType?: boolean
  network?: boolean
  networkName?: boolean
  address?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["depositMethod"]>

export type DepositMethodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  enabled?: boolean
  description?: boolean
  cryptoType?: boolean
  network?: boolean
  networkName?: boolean
  address?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["depositMethod"]>

export type DepositMethodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  enabled?: boolean
  description?: boolean
  cryptoType?: boolean
  network?: boolean
  networkName?: boolean
  address?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["depositMethod"]>

export type DepositMethodSelectScalar = {
  id?: boolean
  name?: boolean
  enabled?: boolean
  description?: boolean
  cryptoType?: boolean
  network?: boolean
  networkName?: boolean
  address?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DepositMethodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "enabled" | "description" | "cryptoType" | "network" | "networkName" | "address" | "createdAt" | "updatedAt", ExtArgs["result"]["depositMethod"]>

export type $DepositMethodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DepositMethod"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    enabled: boolean
    description: string | null
    cryptoType: string | null
    network: string | null
    networkName: string | null
    address: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["depositMethod"]>
  composites: {}
}

export type DepositMethodGetPayload<S extends boolean | null | undefined | DepositMethodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload, S>

export type DepositMethodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DepositMethodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DepositMethodCountAggregateInputType | true
  }

export interface DepositMethodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DepositMethod'], meta: { name: 'DepositMethod' } }
  /**
   * Find zero or one DepositMethod that matches the filter.
   * @param {DepositMethodFindUniqueArgs} args - Arguments to find a DepositMethod
   * @example
   * // Get one DepositMethod
   * const depositMethod = await prisma.depositMethod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DepositMethodFindUniqueArgs>(args: Prisma.SelectSubset<T, DepositMethodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DepositMethodClient<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DepositMethod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DepositMethodFindUniqueOrThrowArgs} args - Arguments to find a DepositMethod
   * @example
   * // Get one DepositMethod
   * const depositMethod = await prisma.depositMethod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DepositMethodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DepositMethodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DepositMethodClient<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DepositMethod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepositMethodFindFirstArgs} args - Arguments to find a DepositMethod
   * @example
   * // Get one DepositMethod
   * const depositMethod = await prisma.depositMethod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DepositMethodFindFirstArgs>(args?: Prisma.SelectSubset<T, DepositMethodFindFirstArgs<ExtArgs>>): Prisma.Prisma__DepositMethodClient<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DepositMethod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepositMethodFindFirstOrThrowArgs} args - Arguments to find a DepositMethod
   * @example
   * // Get one DepositMethod
   * const depositMethod = await prisma.depositMethod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DepositMethodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DepositMethodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DepositMethodClient<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DepositMethods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepositMethodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DepositMethods
   * const depositMethods = await prisma.depositMethod.findMany()
   * 
   * // Get first 10 DepositMethods
   * const depositMethods = await prisma.depositMethod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const depositMethodWithIdOnly = await prisma.depositMethod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DepositMethodFindManyArgs>(args?: Prisma.SelectSubset<T, DepositMethodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DepositMethod.
   * @param {DepositMethodCreateArgs} args - Arguments to create a DepositMethod.
   * @example
   * // Create one DepositMethod
   * const DepositMethod = await prisma.depositMethod.create({
   *   data: {
   *     // ... data to create a DepositMethod
   *   }
   * })
   * 
   */
  create<T extends DepositMethodCreateArgs>(args: Prisma.SelectSubset<T, DepositMethodCreateArgs<ExtArgs>>): Prisma.Prisma__DepositMethodClient<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DepositMethods.
   * @param {DepositMethodCreateManyArgs} args - Arguments to create many DepositMethods.
   * @example
   * // Create many DepositMethods
   * const depositMethod = await prisma.depositMethod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DepositMethodCreateManyArgs>(args?: Prisma.SelectSubset<T, DepositMethodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DepositMethods and returns the data saved in the database.
   * @param {DepositMethodCreateManyAndReturnArgs} args - Arguments to create many DepositMethods.
   * @example
   * // Create many DepositMethods
   * const depositMethod = await prisma.depositMethod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DepositMethods and only return the `id`
   * const depositMethodWithIdOnly = await prisma.depositMethod.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DepositMethodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DepositMethodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DepositMethod.
   * @param {DepositMethodDeleteArgs} args - Arguments to delete one DepositMethod.
   * @example
   * // Delete one DepositMethod
   * const DepositMethod = await prisma.depositMethod.delete({
   *   where: {
   *     // ... filter to delete one DepositMethod
   *   }
   * })
   * 
   */
  delete<T extends DepositMethodDeleteArgs>(args: Prisma.SelectSubset<T, DepositMethodDeleteArgs<ExtArgs>>): Prisma.Prisma__DepositMethodClient<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DepositMethod.
   * @param {DepositMethodUpdateArgs} args - Arguments to update one DepositMethod.
   * @example
   * // Update one DepositMethod
   * const depositMethod = await prisma.depositMethod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DepositMethodUpdateArgs>(args: Prisma.SelectSubset<T, DepositMethodUpdateArgs<ExtArgs>>): Prisma.Prisma__DepositMethodClient<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DepositMethods.
   * @param {DepositMethodDeleteManyArgs} args - Arguments to filter DepositMethods to delete.
   * @example
   * // Delete a few DepositMethods
   * const { count } = await prisma.depositMethod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DepositMethodDeleteManyArgs>(args?: Prisma.SelectSubset<T, DepositMethodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DepositMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepositMethodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DepositMethods
   * const depositMethod = await prisma.depositMethod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DepositMethodUpdateManyArgs>(args: Prisma.SelectSubset<T, DepositMethodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DepositMethods and returns the data updated in the database.
   * @param {DepositMethodUpdateManyAndReturnArgs} args - Arguments to update many DepositMethods.
   * @example
   * // Update many DepositMethods
   * const depositMethod = await prisma.depositMethod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DepositMethods and only return the `id`
   * const depositMethodWithIdOnly = await prisma.depositMethod.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DepositMethodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DepositMethodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DepositMethod.
   * @param {DepositMethodUpsertArgs} args - Arguments to update or create a DepositMethod.
   * @example
   * // Update or create a DepositMethod
   * const depositMethod = await prisma.depositMethod.upsert({
   *   create: {
   *     // ... data to create a DepositMethod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DepositMethod we want to update
   *   }
   * })
   */
  upsert<T extends DepositMethodUpsertArgs>(args: Prisma.SelectSubset<T, DepositMethodUpsertArgs<ExtArgs>>): Prisma.Prisma__DepositMethodClient<runtime.Types.Result.GetResult<Prisma.$DepositMethodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DepositMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepositMethodCountArgs} args - Arguments to filter DepositMethods to count.
   * @example
   * // Count the number of DepositMethods
   * const count = await prisma.depositMethod.count({
   *   where: {
   *     // ... the filter for the DepositMethods we want to count
   *   }
   * })
  **/
  count<T extends DepositMethodCountArgs>(
    args?: Prisma.Subset<T, DepositMethodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DepositMethodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DepositMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepositMethodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DepositMethodAggregateArgs>(args: Prisma.Subset<T, DepositMethodAggregateArgs>): Prisma.PrismaPromise<GetDepositMethodAggregateType<T>>

  /**
   * Group by DepositMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepositMethodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DepositMethodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DepositMethodGroupByArgs['orderBy'] }
      : { orderBy?: DepositMethodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DepositMethodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDepositMethodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DepositMethod model
 */
readonly fields: DepositMethodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DepositMethod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DepositMethodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DepositMethod model
 */
export interface DepositMethodFieldRefs {
  readonly id: Prisma.FieldRef<"DepositMethod", 'String'>
  readonly name: Prisma.FieldRef<"DepositMethod", 'String'>
  readonly enabled: Prisma.FieldRef<"DepositMethod", 'Boolean'>
  readonly description: Prisma.FieldRef<"DepositMethod", 'String'>
  readonly cryptoType: Prisma.FieldRef<"DepositMethod", 'String'>
  readonly network: Prisma.FieldRef<"DepositMethod", 'String'>
  readonly networkName: Prisma.FieldRef<"DepositMethod", 'String'>
  readonly address: Prisma.FieldRef<"DepositMethod", 'String'>
  readonly createdAt: Prisma.FieldRef<"DepositMethod", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DepositMethod", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DepositMethod findUnique
 */
export type DepositMethodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * Filter, which DepositMethod to fetch.
   */
  where: Prisma.DepositMethodWhereUniqueInput
}

/**
 * DepositMethod findUniqueOrThrow
 */
export type DepositMethodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * Filter, which DepositMethod to fetch.
   */
  where: Prisma.DepositMethodWhereUniqueInput
}

/**
 * DepositMethod findFirst
 */
export type DepositMethodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * Filter, which DepositMethod to fetch.
   */
  where?: Prisma.DepositMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DepositMethods to fetch.
   */
  orderBy?: Prisma.DepositMethodOrderByWithRelationInput | Prisma.DepositMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DepositMethods.
   */
  cursor?: Prisma.DepositMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DepositMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DepositMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DepositMethods.
   */
  distinct?: Prisma.DepositMethodScalarFieldEnum | Prisma.DepositMethodScalarFieldEnum[]
}

/**
 * DepositMethod findFirstOrThrow
 */
export type DepositMethodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * Filter, which DepositMethod to fetch.
   */
  where?: Prisma.DepositMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DepositMethods to fetch.
   */
  orderBy?: Prisma.DepositMethodOrderByWithRelationInput | Prisma.DepositMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DepositMethods.
   */
  cursor?: Prisma.DepositMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DepositMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DepositMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DepositMethods.
   */
  distinct?: Prisma.DepositMethodScalarFieldEnum | Prisma.DepositMethodScalarFieldEnum[]
}

/**
 * DepositMethod findMany
 */
export type DepositMethodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * Filter, which DepositMethods to fetch.
   */
  where?: Prisma.DepositMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DepositMethods to fetch.
   */
  orderBy?: Prisma.DepositMethodOrderByWithRelationInput | Prisma.DepositMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DepositMethods.
   */
  cursor?: Prisma.DepositMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DepositMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DepositMethods.
   */
  skip?: number
  distinct?: Prisma.DepositMethodScalarFieldEnum | Prisma.DepositMethodScalarFieldEnum[]
}

/**
 * DepositMethod create
 */
export type DepositMethodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * The data needed to create a DepositMethod.
   */
  data: Prisma.XOR<Prisma.DepositMethodCreateInput, Prisma.DepositMethodUncheckedCreateInput>
}

/**
 * DepositMethod createMany
 */
export type DepositMethodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DepositMethods.
   */
  data: Prisma.DepositMethodCreateManyInput | Prisma.DepositMethodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DepositMethod createManyAndReturn
 */
export type DepositMethodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * The data used to create many DepositMethods.
   */
  data: Prisma.DepositMethodCreateManyInput | Prisma.DepositMethodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DepositMethod update
 */
export type DepositMethodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * The data needed to update a DepositMethod.
   */
  data: Prisma.XOR<Prisma.DepositMethodUpdateInput, Prisma.DepositMethodUncheckedUpdateInput>
  /**
   * Choose, which DepositMethod to update.
   */
  where: Prisma.DepositMethodWhereUniqueInput
}

/**
 * DepositMethod updateMany
 */
export type DepositMethodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DepositMethods.
   */
  data: Prisma.XOR<Prisma.DepositMethodUpdateManyMutationInput, Prisma.DepositMethodUncheckedUpdateManyInput>
  /**
   * Filter which DepositMethods to update
   */
  where?: Prisma.DepositMethodWhereInput
  /**
   * Limit how many DepositMethods to update.
   */
  limit?: number
}

/**
 * DepositMethod updateManyAndReturn
 */
export type DepositMethodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * The data used to update DepositMethods.
   */
  data: Prisma.XOR<Prisma.DepositMethodUpdateManyMutationInput, Prisma.DepositMethodUncheckedUpdateManyInput>
  /**
   * Filter which DepositMethods to update
   */
  where?: Prisma.DepositMethodWhereInput
  /**
   * Limit how many DepositMethods to update.
   */
  limit?: number
}

/**
 * DepositMethod upsert
 */
export type DepositMethodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * The filter to search for the DepositMethod to update in case it exists.
   */
  where: Prisma.DepositMethodWhereUniqueInput
  /**
   * In case the DepositMethod found by the `where` argument doesn't exist, create a new DepositMethod with this data.
   */
  create: Prisma.XOR<Prisma.DepositMethodCreateInput, Prisma.DepositMethodUncheckedCreateInput>
  /**
   * In case the DepositMethod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DepositMethodUpdateInput, Prisma.DepositMethodUncheckedUpdateInput>
}

/**
 * DepositMethod delete
 */
export type DepositMethodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
  /**
   * Filter which DepositMethod to delete.
   */
  where: Prisma.DepositMethodWhereUniqueInput
}

/**
 * DepositMethod deleteMany
 */
export type DepositMethodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DepositMethods to delete
   */
  where?: Prisma.DepositMethodWhereInput
  /**
   * Limit how many DepositMethods to delete.
   */
  limit?: number
}

/**
 * DepositMethod without action
 */
export type DepositMethodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepositMethod
   */
  select?: Prisma.DepositMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DepositMethod
   */
  omit?: Prisma.DepositMethodOmit<ExtArgs> | null
}
