
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PostedTrade` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PostedTrade
 * 
 */
export type PostedTradeModel = runtime.Types.Result.DefaultSelection<Prisma.$PostedTradePayload>

export type AggregatePostedTrade = {
  _count: PostedTradeCountAggregateOutputType | null
  _avg: PostedTradeAvgAggregateOutputType | null
  _sum: PostedTradeSumAggregateOutputType | null
  _min: PostedTradeMinAggregateOutputType | null
  _max: PostedTradeMaxAggregateOutputType | null
}

export type PostedTradeAvgAggregateOutputType = {
  followers: number | null
  winRate: number | null
  wins: number | null
  losses: number | null
  trades: number | null
  minStartup: number | null
  duration: number | null
  entryPrice: number | null
  profitShare: number | null
  amount: number | null
}

export type PostedTradeSumAggregateOutputType = {
  followers: number | null
  winRate: number | null
  wins: number | null
  losses: number | null
  trades: number | null
  minStartup: number | null
  duration: number | null
  entryPrice: number | null
  profitShare: number | null
  amount: number | null
}

export type PostedTradeMinAggregateOutputType = {
  id: string | null
  userId: string | null
  assetId: string | null
  name: string | null
  username: string | null
  followers: number | null
  winRate: number | null
  wins: number | null
  losses: number | null
  trades: number | null
  minStartup: number | null
  status: string | null
  duration: number | null
  entryPrice: number | null
  tradeType: string | null
  profitShare: number | null
  amount: number | null
  notes: string | null
  isAdminPosted: boolean | null
  createdAt: Date | null
}

export type PostedTradeMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  assetId: string | null
  name: string | null
  username: string | null
  followers: number | null
  winRate: number | null
  wins: number | null
  losses: number | null
  trades: number | null
  minStartup: number | null
  status: string | null
  duration: number | null
  entryPrice: number | null
  tradeType: string | null
  profitShare: number | null
  amount: number | null
  notes: string | null
  isAdminPosted: boolean | null
  createdAt: Date | null
}

export type PostedTradeCountAggregateOutputType = {
  id: number
  userId: number
  assetId: number
  name: number
  username: number
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status: number
  duration: number
  entryPrice: number
  tradeType: number
  profitShare: number
  amount: number
  notes: number
  isAdminPosted: number
  createdAt: number
  _all: number
}


export type PostedTradeAvgAggregateInputType = {
  followers?: true
  winRate?: true
  wins?: true
  losses?: true
  trades?: true
  minStartup?: true
  duration?: true
  entryPrice?: true
  profitShare?: true
  amount?: true
}

export type PostedTradeSumAggregateInputType = {
  followers?: true
  winRate?: true
  wins?: true
  losses?: true
  trades?: true
  minStartup?: true
  duration?: true
  entryPrice?: true
  profitShare?: true
  amount?: true
}

export type PostedTradeMinAggregateInputType = {
  id?: true
  userId?: true
  assetId?: true
  name?: true
  username?: true
  followers?: true
  winRate?: true
  wins?: true
  losses?: true
  trades?: true
  minStartup?: true
  status?: true
  duration?: true
  entryPrice?: true
  tradeType?: true
  profitShare?: true
  amount?: true
  notes?: true
  isAdminPosted?: true
  createdAt?: true
}

export type PostedTradeMaxAggregateInputType = {
  id?: true
  userId?: true
  assetId?: true
  name?: true
  username?: true
  followers?: true
  winRate?: true
  wins?: true
  losses?: true
  trades?: true
  minStartup?: true
  status?: true
  duration?: true
  entryPrice?: true
  tradeType?: true
  profitShare?: true
  amount?: true
  notes?: true
  isAdminPosted?: true
  createdAt?: true
}

export type PostedTradeCountAggregateInputType = {
  id?: true
  userId?: true
  assetId?: true
  name?: true
  username?: true
  followers?: true
  winRate?: true
  wins?: true
  losses?: true
  trades?: true
  minStartup?: true
  status?: true
  duration?: true
  entryPrice?: true
  tradeType?: true
  profitShare?: true
  amount?: true
  notes?: true
  isAdminPosted?: true
  createdAt?: true
  _all?: true
}

export type PostedTradeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PostedTrade to aggregate.
   */
  where?: Prisma.PostedTradeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostedTrades to fetch.
   */
  orderBy?: Prisma.PostedTradeOrderByWithRelationInput | Prisma.PostedTradeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PostedTradeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostedTrades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostedTrades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PostedTrades
  **/
  _count?: true | PostedTradeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PostedTradeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PostedTradeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PostedTradeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PostedTradeMaxAggregateInputType
}

export type GetPostedTradeAggregateType<T extends PostedTradeAggregateArgs> = {
      [P in keyof T & keyof AggregatePostedTrade]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePostedTrade[P]>
    : Prisma.GetScalarType<T[P], AggregatePostedTrade[P]>
}




export type PostedTradeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostedTradeWhereInput
  orderBy?: Prisma.PostedTradeOrderByWithAggregationInput | Prisma.PostedTradeOrderByWithAggregationInput[]
  by: Prisma.PostedTradeScalarFieldEnum[] | Prisma.PostedTradeScalarFieldEnum
  having?: Prisma.PostedTradeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PostedTradeCountAggregateInputType | true
  _avg?: PostedTradeAvgAggregateInputType
  _sum?: PostedTradeSumAggregateInputType
  _min?: PostedTradeMinAggregateInputType
  _max?: PostedTradeMaxAggregateInputType
}

export type PostedTradeGroupByOutputType = {
  id: string
  userId: string
  assetId: string | null
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status: string
  duration: number
  entryPrice: number | null
  tradeType: string | null
  profitShare: number | null
  amount: number | null
  notes: string | null
  isAdminPosted: boolean
  createdAt: Date
  _count: PostedTradeCountAggregateOutputType | null
  _avg: PostedTradeAvgAggregateOutputType | null
  _sum: PostedTradeSumAggregateOutputType | null
  _min: PostedTradeMinAggregateOutputType | null
  _max: PostedTradeMaxAggregateOutputType | null
}

type GetPostedTradeGroupByPayload<T extends PostedTradeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PostedTradeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PostedTradeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PostedTradeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PostedTradeGroupByOutputType[P]>
      }
    >
  >



export type PostedTradeWhereInput = {
  AND?: Prisma.PostedTradeWhereInput | Prisma.PostedTradeWhereInput[]
  OR?: Prisma.PostedTradeWhereInput[]
  NOT?: Prisma.PostedTradeWhereInput | Prisma.PostedTradeWhereInput[]
  id?: Prisma.StringFilter<"PostedTrade"> | string
  userId?: Prisma.StringFilter<"PostedTrade"> | string
  assetId?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  name?: Prisma.StringFilter<"PostedTrade"> | string
  username?: Prisma.StringFilter<"PostedTrade"> | string
  followers?: Prisma.IntFilter<"PostedTrade"> | number
  winRate?: Prisma.FloatFilter<"PostedTrade"> | number
  wins?: Prisma.IntFilter<"PostedTrade"> | number
  losses?: Prisma.IntFilter<"PostedTrade"> | number
  trades?: Prisma.IntFilter<"PostedTrade"> | number
  minStartup?: Prisma.FloatFilter<"PostedTrade"> | number
  status?: Prisma.StringFilter<"PostedTrade"> | string
  duration?: Prisma.IntFilter<"PostedTrade"> | number
  entryPrice?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  tradeType?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  profitShare?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  amount?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  notes?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  isAdminPosted?: Prisma.BoolFilter<"PostedTrade"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PostedTrade"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  asset?: Prisma.XOR<Prisma.AssetNullableScalarRelationFilter, Prisma.AssetWhereInput> | null
}

export type PostedTradeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  username?: Prisma.SortOrder
  followers?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  trades?: Prisma.SortOrder
  minStartup?: Prisma.SortOrder
  status?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  entryPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  tradeType?: Prisma.SortOrderInput | Prisma.SortOrder
  profitShare?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isAdminPosted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  asset?: Prisma.AssetOrderByWithRelationInput
}

export type PostedTradeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PostedTradeWhereInput | Prisma.PostedTradeWhereInput[]
  OR?: Prisma.PostedTradeWhereInput[]
  NOT?: Prisma.PostedTradeWhereInput | Prisma.PostedTradeWhereInput[]
  userId?: Prisma.StringFilter<"PostedTrade"> | string
  assetId?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  name?: Prisma.StringFilter<"PostedTrade"> | string
  username?: Prisma.StringFilter<"PostedTrade"> | string
  followers?: Prisma.IntFilter<"PostedTrade"> | number
  winRate?: Prisma.FloatFilter<"PostedTrade"> | number
  wins?: Prisma.IntFilter<"PostedTrade"> | number
  losses?: Prisma.IntFilter<"PostedTrade"> | number
  trades?: Prisma.IntFilter<"PostedTrade"> | number
  minStartup?: Prisma.FloatFilter<"PostedTrade"> | number
  status?: Prisma.StringFilter<"PostedTrade"> | string
  duration?: Prisma.IntFilter<"PostedTrade"> | number
  entryPrice?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  tradeType?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  profitShare?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  amount?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  notes?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  isAdminPosted?: Prisma.BoolFilter<"PostedTrade"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PostedTrade"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  asset?: Prisma.XOR<Prisma.AssetNullableScalarRelationFilter, Prisma.AssetWhereInput> | null
}, "id">

export type PostedTradeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  username?: Prisma.SortOrder
  followers?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  trades?: Prisma.SortOrder
  minStartup?: Prisma.SortOrder
  status?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  entryPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  tradeType?: Prisma.SortOrderInput | Prisma.SortOrder
  profitShare?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isAdminPosted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PostedTradeCountOrderByAggregateInput
  _avg?: Prisma.PostedTradeAvgOrderByAggregateInput
  _max?: Prisma.PostedTradeMaxOrderByAggregateInput
  _min?: Prisma.PostedTradeMinOrderByAggregateInput
  _sum?: Prisma.PostedTradeSumOrderByAggregateInput
}

export type PostedTradeScalarWhereWithAggregatesInput = {
  AND?: Prisma.PostedTradeScalarWhereWithAggregatesInput | Prisma.PostedTradeScalarWhereWithAggregatesInput[]
  OR?: Prisma.PostedTradeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PostedTradeScalarWhereWithAggregatesInput | Prisma.PostedTradeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PostedTrade"> | string
  userId?: Prisma.StringWithAggregatesFilter<"PostedTrade"> | string
  assetId?: Prisma.StringNullableWithAggregatesFilter<"PostedTrade"> | string | null
  name?: Prisma.StringWithAggregatesFilter<"PostedTrade"> | string
  username?: Prisma.StringWithAggregatesFilter<"PostedTrade"> | string
  followers?: Prisma.IntWithAggregatesFilter<"PostedTrade"> | number
  winRate?: Prisma.FloatWithAggregatesFilter<"PostedTrade"> | number
  wins?: Prisma.IntWithAggregatesFilter<"PostedTrade"> | number
  losses?: Prisma.IntWithAggregatesFilter<"PostedTrade"> | number
  trades?: Prisma.IntWithAggregatesFilter<"PostedTrade"> | number
  minStartup?: Prisma.FloatWithAggregatesFilter<"PostedTrade"> | number
  status?: Prisma.StringWithAggregatesFilter<"PostedTrade"> | string
  duration?: Prisma.IntWithAggregatesFilter<"PostedTrade"> | number
  entryPrice?: Prisma.FloatNullableWithAggregatesFilter<"PostedTrade"> | number | null
  tradeType?: Prisma.StringNullableWithAggregatesFilter<"PostedTrade"> | string | null
  profitShare?: Prisma.FloatNullableWithAggregatesFilter<"PostedTrade"> | number | null
  amount?: Prisma.FloatNullableWithAggregatesFilter<"PostedTrade"> | number | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"PostedTrade"> | string | null
  isAdminPosted?: Prisma.BoolWithAggregatesFilter<"PostedTrade"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PostedTrade"> | Date | string
}

export type PostedTradeCreateInput = {
  id?: string
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPostedTradesInput
  asset?: Prisma.AssetCreateNestedOneWithoutPostedTradesInput
}

export type PostedTradeUncheckedCreateInput = {
  id?: string
  userId: string
  assetId?: string | null
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
}

export type PostedTradeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPostedTradesNestedInput
  asset?: Prisma.AssetUpdateOneWithoutPostedTradesNestedInput
}

export type PostedTradeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostedTradeCreateManyInput = {
  id?: string
  userId: string
  assetId?: string | null
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
}

export type PostedTradeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostedTradeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostedTradeListRelationFilter = {
  every?: Prisma.PostedTradeWhereInput
  some?: Prisma.PostedTradeWhereInput
  none?: Prisma.PostedTradeWhereInput
}

export type PostedTradeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PostedTradeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  username?: Prisma.SortOrder
  followers?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  trades?: Prisma.SortOrder
  minStartup?: Prisma.SortOrder
  status?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  entryPrice?: Prisma.SortOrder
  tradeType?: Prisma.SortOrder
  profitShare?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isAdminPosted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PostedTradeAvgOrderByAggregateInput = {
  followers?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  trades?: Prisma.SortOrder
  minStartup?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  entryPrice?: Prisma.SortOrder
  profitShare?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type PostedTradeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  username?: Prisma.SortOrder
  followers?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  trades?: Prisma.SortOrder
  minStartup?: Prisma.SortOrder
  status?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  entryPrice?: Prisma.SortOrder
  tradeType?: Prisma.SortOrder
  profitShare?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isAdminPosted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PostedTradeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  username?: Prisma.SortOrder
  followers?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  trades?: Prisma.SortOrder
  minStartup?: Prisma.SortOrder
  status?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  entryPrice?: Prisma.SortOrder
  tradeType?: Prisma.SortOrder
  profitShare?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isAdminPosted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PostedTradeSumOrderByAggregateInput = {
  followers?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  trades?: Prisma.SortOrder
  minStartup?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  entryPrice?: Prisma.SortOrder
  profitShare?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type PostedTradeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PostedTradeCreateWithoutUserInput, Prisma.PostedTradeUncheckedCreateWithoutUserInput> | Prisma.PostedTradeCreateWithoutUserInput[] | Prisma.PostedTradeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PostedTradeCreateOrConnectWithoutUserInput | Prisma.PostedTradeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PostedTradeCreateManyUserInputEnvelope
  connect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
}

export type PostedTradeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PostedTradeCreateWithoutUserInput, Prisma.PostedTradeUncheckedCreateWithoutUserInput> | Prisma.PostedTradeCreateWithoutUserInput[] | Prisma.PostedTradeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PostedTradeCreateOrConnectWithoutUserInput | Prisma.PostedTradeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PostedTradeCreateManyUserInputEnvelope
  connect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
}

export type PostedTradeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PostedTradeCreateWithoutUserInput, Prisma.PostedTradeUncheckedCreateWithoutUserInput> | Prisma.PostedTradeCreateWithoutUserInput[] | Prisma.PostedTradeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PostedTradeCreateOrConnectWithoutUserInput | Prisma.PostedTradeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PostedTradeUpsertWithWhereUniqueWithoutUserInput | Prisma.PostedTradeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PostedTradeCreateManyUserInputEnvelope
  set?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  disconnect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  delete?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  connect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  update?: Prisma.PostedTradeUpdateWithWhereUniqueWithoutUserInput | Prisma.PostedTradeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PostedTradeUpdateManyWithWhereWithoutUserInput | Prisma.PostedTradeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PostedTradeScalarWhereInput | Prisma.PostedTradeScalarWhereInput[]
}

export type PostedTradeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PostedTradeCreateWithoutUserInput, Prisma.PostedTradeUncheckedCreateWithoutUserInput> | Prisma.PostedTradeCreateWithoutUserInput[] | Prisma.PostedTradeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PostedTradeCreateOrConnectWithoutUserInput | Prisma.PostedTradeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PostedTradeUpsertWithWhereUniqueWithoutUserInput | Prisma.PostedTradeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PostedTradeCreateManyUserInputEnvelope
  set?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  disconnect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  delete?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  connect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  update?: Prisma.PostedTradeUpdateWithWhereUniqueWithoutUserInput | Prisma.PostedTradeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PostedTradeUpdateManyWithWhereWithoutUserInput | Prisma.PostedTradeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PostedTradeScalarWhereInput | Prisma.PostedTradeScalarWhereInput[]
}

export type PostedTradeCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.PostedTradeCreateWithoutAssetInput, Prisma.PostedTradeUncheckedCreateWithoutAssetInput> | Prisma.PostedTradeCreateWithoutAssetInput[] | Prisma.PostedTradeUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.PostedTradeCreateOrConnectWithoutAssetInput | Prisma.PostedTradeCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.PostedTradeCreateManyAssetInputEnvelope
  connect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
}

export type PostedTradeUncheckedCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.PostedTradeCreateWithoutAssetInput, Prisma.PostedTradeUncheckedCreateWithoutAssetInput> | Prisma.PostedTradeCreateWithoutAssetInput[] | Prisma.PostedTradeUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.PostedTradeCreateOrConnectWithoutAssetInput | Prisma.PostedTradeCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.PostedTradeCreateManyAssetInputEnvelope
  connect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
}

export type PostedTradeUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.PostedTradeCreateWithoutAssetInput, Prisma.PostedTradeUncheckedCreateWithoutAssetInput> | Prisma.PostedTradeCreateWithoutAssetInput[] | Prisma.PostedTradeUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.PostedTradeCreateOrConnectWithoutAssetInput | Prisma.PostedTradeCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.PostedTradeUpsertWithWhereUniqueWithoutAssetInput | Prisma.PostedTradeUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.PostedTradeCreateManyAssetInputEnvelope
  set?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  disconnect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  delete?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  connect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  update?: Prisma.PostedTradeUpdateWithWhereUniqueWithoutAssetInput | Prisma.PostedTradeUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.PostedTradeUpdateManyWithWhereWithoutAssetInput | Prisma.PostedTradeUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.PostedTradeScalarWhereInput | Prisma.PostedTradeScalarWhereInput[]
}

export type PostedTradeUncheckedUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.PostedTradeCreateWithoutAssetInput, Prisma.PostedTradeUncheckedCreateWithoutAssetInput> | Prisma.PostedTradeCreateWithoutAssetInput[] | Prisma.PostedTradeUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.PostedTradeCreateOrConnectWithoutAssetInput | Prisma.PostedTradeCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.PostedTradeUpsertWithWhereUniqueWithoutAssetInput | Prisma.PostedTradeUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.PostedTradeCreateManyAssetInputEnvelope
  set?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  disconnect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  delete?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  connect?: Prisma.PostedTradeWhereUniqueInput | Prisma.PostedTradeWhereUniqueInput[]
  update?: Prisma.PostedTradeUpdateWithWhereUniqueWithoutAssetInput | Prisma.PostedTradeUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.PostedTradeUpdateManyWithWhereWithoutAssetInput | Prisma.PostedTradeUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.PostedTradeScalarWhereInput | Prisma.PostedTradeScalarWhereInput[]
}

export type PostedTradeCreateWithoutUserInput = {
  id?: string
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
  asset?: Prisma.AssetCreateNestedOneWithoutPostedTradesInput
}

export type PostedTradeUncheckedCreateWithoutUserInput = {
  id?: string
  assetId?: string | null
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
}

export type PostedTradeCreateOrConnectWithoutUserInput = {
  where: Prisma.PostedTradeWhereUniqueInput
  create: Prisma.XOR<Prisma.PostedTradeCreateWithoutUserInput, Prisma.PostedTradeUncheckedCreateWithoutUserInput>
}

export type PostedTradeCreateManyUserInputEnvelope = {
  data: Prisma.PostedTradeCreateManyUserInput | Prisma.PostedTradeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PostedTradeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PostedTradeWhereUniqueInput
  update: Prisma.XOR<Prisma.PostedTradeUpdateWithoutUserInput, Prisma.PostedTradeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PostedTradeCreateWithoutUserInput, Prisma.PostedTradeUncheckedCreateWithoutUserInput>
}

export type PostedTradeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PostedTradeWhereUniqueInput
  data: Prisma.XOR<Prisma.PostedTradeUpdateWithoutUserInput, Prisma.PostedTradeUncheckedUpdateWithoutUserInput>
}

export type PostedTradeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PostedTradeScalarWhereInput
  data: Prisma.XOR<Prisma.PostedTradeUpdateManyMutationInput, Prisma.PostedTradeUncheckedUpdateManyWithoutUserInput>
}

export type PostedTradeScalarWhereInput = {
  AND?: Prisma.PostedTradeScalarWhereInput | Prisma.PostedTradeScalarWhereInput[]
  OR?: Prisma.PostedTradeScalarWhereInput[]
  NOT?: Prisma.PostedTradeScalarWhereInput | Prisma.PostedTradeScalarWhereInput[]
  id?: Prisma.StringFilter<"PostedTrade"> | string
  userId?: Prisma.StringFilter<"PostedTrade"> | string
  assetId?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  name?: Prisma.StringFilter<"PostedTrade"> | string
  username?: Prisma.StringFilter<"PostedTrade"> | string
  followers?: Prisma.IntFilter<"PostedTrade"> | number
  winRate?: Prisma.FloatFilter<"PostedTrade"> | number
  wins?: Prisma.IntFilter<"PostedTrade"> | number
  losses?: Prisma.IntFilter<"PostedTrade"> | number
  trades?: Prisma.IntFilter<"PostedTrade"> | number
  minStartup?: Prisma.FloatFilter<"PostedTrade"> | number
  status?: Prisma.StringFilter<"PostedTrade"> | string
  duration?: Prisma.IntFilter<"PostedTrade"> | number
  entryPrice?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  tradeType?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  profitShare?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  amount?: Prisma.FloatNullableFilter<"PostedTrade"> | number | null
  notes?: Prisma.StringNullableFilter<"PostedTrade"> | string | null
  isAdminPosted?: Prisma.BoolFilter<"PostedTrade"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PostedTrade"> | Date | string
}

export type PostedTradeCreateWithoutAssetInput = {
  id?: string
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPostedTradesInput
}

export type PostedTradeUncheckedCreateWithoutAssetInput = {
  id?: string
  userId: string
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
}

export type PostedTradeCreateOrConnectWithoutAssetInput = {
  where: Prisma.PostedTradeWhereUniqueInput
  create: Prisma.XOR<Prisma.PostedTradeCreateWithoutAssetInput, Prisma.PostedTradeUncheckedCreateWithoutAssetInput>
}

export type PostedTradeCreateManyAssetInputEnvelope = {
  data: Prisma.PostedTradeCreateManyAssetInput | Prisma.PostedTradeCreateManyAssetInput[]
  skipDuplicates?: boolean
}

export type PostedTradeUpsertWithWhereUniqueWithoutAssetInput = {
  where: Prisma.PostedTradeWhereUniqueInput
  update: Prisma.XOR<Prisma.PostedTradeUpdateWithoutAssetInput, Prisma.PostedTradeUncheckedUpdateWithoutAssetInput>
  create: Prisma.XOR<Prisma.PostedTradeCreateWithoutAssetInput, Prisma.PostedTradeUncheckedCreateWithoutAssetInput>
}

export type PostedTradeUpdateWithWhereUniqueWithoutAssetInput = {
  where: Prisma.PostedTradeWhereUniqueInput
  data: Prisma.XOR<Prisma.PostedTradeUpdateWithoutAssetInput, Prisma.PostedTradeUncheckedUpdateWithoutAssetInput>
}

export type PostedTradeUpdateManyWithWhereWithoutAssetInput = {
  where: Prisma.PostedTradeScalarWhereInput
  data: Prisma.XOR<Prisma.PostedTradeUpdateManyMutationInput, Prisma.PostedTradeUncheckedUpdateManyWithoutAssetInput>
}

export type PostedTradeCreateManyUserInput = {
  id?: string
  assetId?: string | null
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
}

export type PostedTradeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  asset?: Prisma.AssetUpdateOneWithoutPostedTradesNestedInput
}

export type PostedTradeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostedTradeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostedTradeCreateManyAssetInput = {
  id?: string
  userId: string
  name: string
  username: string
  followers: number
  winRate: number
  wins: number
  losses: number
  trades: number
  minStartup: number
  status?: string
  duration?: number
  entryPrice?: number | null
  tradeType?: string | null
  profitShare?: number | null
  amount?: number | null
  notes?: string | null
  isAdminPosted?: boolean
  createdAt?: Date | string
}

export type PostedTradeUpdateWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPostedTradesNestedInput
}

export type PostedTradeUncheckedUpdateWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostedTradeUncheckedUpdateManyWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  followers?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.FloatFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  trades?: Prisma.IntFieldUpdateOperationsInput | number
  minStartup?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  entryPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  tradeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profitShare?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAdminPosted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PostedTradeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  assetId?: boolean
  name?: boolean
  username?: boolean
  followers?: boolean
  winRate?: boolean
  wins?: boolean
  losses?: boolean
  trades?: boolean
  minStartup?: boolean
  status?: boolean
  duration?: boolean
  entryPrice?: boolean
  tradeType?: boolean
  profitShare?: boolean
  amount?: boolean
  notes?: boolean
  isAdminPosted?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.PostedTrade$assetArgs<ExtArgs>
}, ExtArgs["result"]["postedTrade"]>

export type PostedTradeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  assetId?: boolean
  name?: boolean
  username?: boolean
  followers?: boolean
  winRate?: boolean
  wins?: boolean
  losses?: boolean
  trades?: boolean
  minStartup?: boolean
  status?: boolean
  duration?: boolean
  entryPrice?: boolean
  tradeType?: boolean
  profitShare?: boolean
  amount?: boolean
  notes?: boolean
  isAdminPosted?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.PostedTrade$assetArgs<ExtArgs>
}, ExtArgs["result"]["postedTrade"]>

export type PostedTradeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  assetId?: boolean
  name?: boolean
  username?: boolean
  followers?: boolean
  winRate?: boolean
  wins?: boolean
  losses?: boolean
  trades?: boolean
  minStartup?: boolean
  status?: boolean
  duration?: boolean
  entryPrice?: boolean
  tradeType?: boolean
  profitShare?: boolean
  amount?: boolean
  notes?: boolean
  isAdminPosted?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.PostedTrade$assetArgs<ExtArgs>
}, ExtArgs["result"]["postedTrade"]>

export type PostedTradeSelectScalar = {
  id?: boolean
  userId?: boolean
  assetId?: boolean
  name?: boolean
  username?: boolean
  followers?: boolean
  winRate?: boolean
  wins?: boolean
  losses?: boolean
  trades?: boolean
  minStartup?: boolean
  status?: boolean
  duration?: boolean
  entryPrice?: boolean
  tradeType?: boolean
  profitShare?: boolean
  amount?: boolean
  notes?: boolean
  isAdminPosted?: boolean
  createdAt?: boolean
}

export type PostedTradeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "assetId" | "name" | "username" | "followers" | "winRate" | "wins" | "losses" | "trades" | "minStartup" | "status" | "duration" | "entryPrice" | "tradeType" | "profitShare" | "amount" | "notes" | "isAdminPosted" | "createdAt", ExtArgs["result"]["postedTrade"]>
export type PostedTradeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.PostedTrade$assetArgs<ExtArgs>
}
export type PostedTradeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.PostedTrade$assetArgs<ExtArgs>
}
export type PostedTradeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.PostedTrade$assetArgs<ExtArgs>
}

export type $PostedTradePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PostedTrade"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    asset: Prisma.$AssetPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    assetId: string | null
    name: string
    username: string
    followers: number
    winRate: number
    wins: number
    losses: number
    trades: number
    minStartup: number
    status: string
    duration: number
    entryPrice: number | null
    tradeType: string | null
    profitShare: number | null
    amount: number | null
    notes: string | null
    isAdminPosted: boolean
    createdAt: Date
  }, ExtArgs["result"]["postedTrade"]>
  composites: {}
}

export type PostedTradeGetPayload<S extends boolean | null | undefined | PostedTradeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PostedTradePayload, S>

export type PostedTradeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PostedTradeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PostedTradeCountAggregateInputType | true
  }

export interface PostedTradeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PostedTrade'], meta: { name: 'PostedTrade' } }
  /**
   * Find zero or one PostedTrade that matches the filter.
   * @param {PostedTradeFindUniqueArgs} args - Arguments to find a PostedTrade
   * @example
   * // Get one PostedTrade
   * const postedTrade = await prisma.postedTrade.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PostedTradeFindUniqueArgs>(args: Prisma.SelectSubset<T, PostedTradeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PostedTradeClient<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PostedTrade that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PostedTradeFindUniqueOrThrowArgs} args - Arguments to find a PostedTrade
   * @example
   * // Get one PostedTrade
   * const postedTrade = await prisma.postedTrade.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PostedTradeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PostedTradeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PostedTradeClient<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PostedTrade that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostedTradeFindFirstArgs} args - Arguments to find a PostedTrade
   * @example
   * // Get one PostedTrade
   * const postedTrade = await prisma.postedTrade.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PostedTradeFindFirstArgs>(args?: Prisma.SelectSubset<T, PostedTradeFindFirstArgs<ExtArgs>>): Prisma.Prisma__PostedTradeClient<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PostedTrade that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostedTradeFindFirstOrThrowArgs} args - Arguments to find a PostedTrade
   * @example
   * // Get one PostedTrade
   * const postedTrade = await prisma.postedTrade.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PostedTradeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PostedTradeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PostedTradeClient<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PostedTrades that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostedTradeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PostedTrades
   * const postedTrades = await prisma.postedTrade.findMany()
   * 
   * // Get first 10 PostedTrades
   * const postedTrades = await prisma.postedTrade.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const postedTradeWithIdOnly = await prisma.postedTrade.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PostedTradeFindManyArgs>(args?: Prisma.SelectSubset<T, PostedTradeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PostedTrade.
   * @param {PostedTradeCreateArgs} args - Arguments to create a PostedTrade.
   * @example
   * // Create one PostedTrade
   * const PostedTrade = await prisma.postedTrade.create({
   *   data: {
   *     // ... data to create a PostedTrade
   *   }
   * })
   * 
   */
  create<T extends PostedTradeCreateArgs>(args: Prisma.SelectSubset<T, PostedTradeCreateArgs<ExtArgs>>): Prisma.Prisma__PostedTradeClient<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PostedTrades.
   * @param {PostedTradeCreateManyArgs} args - Arguments to create many PostedTrades.
   * @example
   * // Create many PostedTrades
   * const postedTrade = await prisma.postedTrade.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PostedTradeCreateManyArgs>(args?: Prisma.SelectSubset<T, PostedTradeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PostedTrades and returns the data saved in the database.
   * @param {PostedTradeCreateManyAndReturnArgs} args - Arguments to create many PostedTrades.
   * @example
   * // Create many PostedTrades
   * const postedTrade = await prisma.postedTrade.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PostedTrades and only return the `id`
   * const postedTradeWithIdOnly = await prisma.postedTrade.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PostedTradeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PostedTradeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PostedTrade.
   * @param {PostedTradeDeleteArgs} args - Arguments to delete one PostedTrade.
   * @example
   * // Delete one PostedTrade
   * const PostedTrade = await prisma.postedTrade.delete({
   *   where: {
   *     // ... filter to delete one PostedTrade
   *   }
   * })
   * 
   */
  delete<T extends PostedTradeDeleteArgs>(args: Prisma.SelectSubset<T, PostedTradeDeleteArgs<ExtArgs>>): Prisma.Prisma__PostedTradeClient<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PostedTrade.
   * @param {PostedTradeUpdateArgs} args - Arguments to update one PostedTrade.
   * @example
   * // Update one PostedTrade
   * const postedTrade = await prisma.postedTrade.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PostedTradeUpdateArgs>(args: Prisma.SelectSubset<T, PostedTradeUpdateArgs<ExtArgs>>): Prisma.Prisma__PostedTradeClient<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PostedTrades.
   * @param {PostedTradeDeleteManyArgs} args - Arguments to filter PostedTrades to delete.
   * @example
   * // Delete a few PostedTrades
   * const { count } = await prisma.postedTrade.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PostedTradeDeleteManyArgs>(args?: Prisma.SelectSubset<T, PostedTradeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PostedTrades.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostedTradeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PostedTrades
   * const postedTrade = await prisma.postedTrade.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PostedTradeUpdateManyArgs>(args: Prisma.SelectSubset<T, PostedTradeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PostedTrades and returns the data updated in the database.
   * @param {PostedTradeUpdateManyAndReturnArgs} args - Arguments to update many PostedTrades.
   * @example
   * // Update many PostedTrades
   * const postedTrade = await prisma.postedTrade.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PostedTrades and only return the `id`
   * const postedTradeWithIdOnly = await prisma.postedTrade.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PostedTradeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PostedTradeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PostedTrade.
   * @param {PostedTradeUpsertArgs} args - Arguments to update or create a PostedTrade.
   * @example
   * // Update or create a PostedTrade
   * const postedTrade = await prisma.postedTrade.upsert({
   *   create: {
   *     // ... data to create a PostedTrade
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PostedTrade we want to update
   *   }
   * })
   */
  upsert<T extends PostedTradeUpsertArgs>(args: Prisma.SelectSubset<T, PostedTradeUpsertArgs<ExtArgs>>): Prisma.Prisma__PostedTradeClient<runtime.Types.Result.GetResult<Prisma.$PostedTradePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PostedTrades.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostedTradeCountArgs} args - Arguments to filter PostedTrades to count.
   * @example
   * // Count the number of PostedTrades
   * const count = await prisma.postedTrade.count({
   *   where: {
   *     // ... the filter for the PostedTrades we want to count
   *   }
   * })
  **/
  count<T extends PostedTradeCountArgs>(
    args?: Prisma.Subset<T, PostedTradeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PostedTradeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PostedTrade.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostedTradeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PostedTradeAggregateArgs>(args: Prisma.Subset<T, PostedTradeAggregateArgs>): Prisma.PrismaPromise<GetPostedTradeAggregateType<T>>

  /**
   * Group by PostedTrade.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostedTradeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PostedTradeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PostedTradeGroupByArgs['orderBy'] }
      : { orderBy?: PostedTradeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PostedTradeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostedTradeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PostedTrade model
 */
readonly fields: PostedTradeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PostedTrade.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PostedTradeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  asset<T extends Prisma.PostedTrade$assetArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PostedTrade$assetArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PostedTrade model
 */
export interface PostedTradeFieldRefs {
  readonly id: Prisma.FieldRef<"PostedTrade", 'String'>
  readonly userId: Prisma.FieldRef<"PostedTrade", 'String'>
  readonly assetId: Prisma.FieldRef<"PostedTrade", 'String'>
  readonly name: Prisma.FieldRef<"PostedTrade", 'String'>
  readonly username: Prisma.FieldRef<"PostedTrade", 'String'>
  readonly followers: Prisma.FieldRef<"PostedTrade", 'Int'>
  readonly winRate: Prisma.FieldRef<"PostedTrade", 'Float'>
  readonly wins: Prisma.FieldRef<"PostedTrade", 'Int'>
  readonly losses: Prisma.FieldRef<"PostedTrade", 'Int'>
  readonly trades: Prisma.FieldRef<"PostedTrade", 'Int'>
  readonly minStartup: Prisma.FieldRef<"PostedTrade", 'Float'>
  readonly status: Prisma.FieldRef<"PostedTrade", 'String'>
  readonly duration: Prisma.FieldRef<"PostedTrade", 'Int'>
  readonly entryPrice: Prisma.FieldRef<"PostedTrade", 'Float'>
  readonly tradeType: Prisma.FieldRef<"PostedTrade", 'String'>
  readonly profitShare: Prisma.FieldRef<"PostedTrade", 'Float'>
  readonly amount: Prisma.FieldRef<"PostedTrade", 'Float'>
  readonly notes: Prisma.FieldRef<"PostedTrade", 'String'>
  readonly isAdminPosted: Prisma.FieldRef<"PostedTrade", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"PostedTrade", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PostedTrade findUnique
 */
export type PostedTradeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * Filter, which PostedTrade to fetch.
   */
  where: Prisma.PostedTradeWhereUniqueInput
}

/**
 * PostedTrade findUniqueOrThrow
 */
export type PostedTradeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * Filter, which PostedTrade to fetch.
   */
  where: Prisma.PostedTradeWhereUniqueInput
}

/**
 * PostedTrade findFirst
 */
export type PostedTradeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * Filter, which PostedTrade to fetch.
   */
  where?: Prisma.PostedTradeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostedTrades to fetch.
   */
  orderBy?: Prisma.PostedTradeOrderByWithRelationInput | Prisma.PostedTradeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PostedTrades.
   */
  cursor?: Prisma.PostedTradeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostedTrades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostedTrades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostedTrades.
   */
  distinct?: Prisma.PostedTradeScalarFieldEnum | Prisma.PostedTradeScalarFieldEnum[]
}

/**
 * PostedTrade findFirstOrThrow
 */
export type PostedTradeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * Filter, which PostedTrade to fetch.
   */
  where?: Prisma.PostedTradeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostedTrades to fetch.
   */
  orderBy?: Prisma.PostedTradeOrderByWithRelationInput | Prisma.PostedTradeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PostedTrades.
   */
  cursor?: Prisma.PostedTradeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostedTrades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostedTrades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostedTrades.
   */
  distinct?: Prisma.PostedTradeScalarFieldEnum | Prisma.PostedTradeScalarFieldEnum[]
}

/**
 * PostedTrade findMany
 */
export type PostedTradeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * Filter, which PostedTrades to fetch.
   */
  where?: Prisma.PostedTradeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostedTrades to fetch.
   */
  orderBy?: Prisma.PostedTradeOrderByWithRelationInput | Prisma.PostedTradeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PostedTrades.
   */
  cursor?: Prisma.PostedTradeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostedTrades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostedTrades.
   */
  skip?: number
  distinct?: Prisma.PostedTradeScalarFieldEnum | Prisma.PostedTradeScalarFieldEnum[]
}

/**
 * PostedTrade create
 */
export type PostedTradeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * The data needed to create a PostedTrade.
   */
  data: Prisma.XOR<Prisma.PostedTradeCreateInput, Prisma.PostedTradeUncheckedCreateInput>
}

/**
 * PostedTrade createMany
 */
export type PostedTradeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PostedTrades.
   */
  data: Prisma.PostedTradeCreateManyInput | Prisma.PostedTradeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PostedTrade createManyAndReturn
 */
export type PostedTradeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * The data used to create many PostedTrades.
   */
  data: Prisma.PostedTradeCreateManyInput | Prisma.PostedTradeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PostedTrade update
 */
export type PostedTradeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * The data needed to update a PostedTrade.
   */
  data: Prisma.XOR<Prisma.PostedTradeUpdateInput, Prisma.PostedTradeUncheckedUpdateInput>
  /**
   * Choose, which PostedTrade to update.
   */
  where: Prisma.PostedTradeWhereUniqueInput
}

/**
 * PostedTrade updateMany
 */
export type PostedTradeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PostedTrades.
   */
  data: Prisma.XOR<Prisma.PostedTradeUpdateManyMutationInput, Prisma.PostedTradeUncheckedUpdateManyInput>
  /**
   * Filter which PostedTrades to update
   */
  where?: Prisma.PostedTradeWhereInput
  /**
   * Limit how many PostedTrades to update.
   */
  limit?: number
}

/**
 * PostedTrade updateManyAndReturn
 */
export type PostedTradeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * The data used to update PostedTrades.
   */
  data: Prisma.XOR<Prisma.PostedTradeUpdateManyMutationInput, Prisma.PostedTradeUncheckedUpdateManyInput>
  /**
   * Filter which PostedTrades to update
   */
  where?: Prisma.PostedTradeWhereInput
  /**
   * Limit how many PostedTrades to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PostedTrade upsert
 */
export type PostedTradeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * The filter to search for the PostedTrade to update in case it exists.
   */
  where: Prisma.PostedTradeWhereUniqueInput
  /**
   * In case the PostedTrade found by the `where` argument doesn't exist, create a new PostedTrade with this data.
   */
  create: Prisma.XOR<Prisma.PostedTradeCreateInput, Prisma.PostedTradeUncheckedCreateInput>
  /**
   * In case the PostedTrade was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PostedTradeUpdateInput, Prisma.PostedTradeUncheckedUpdateInput>
}

/**
 * PostedTrade delete
 */
export type PostedTradeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
  /**
   * Filter which PostedTrade to delete.
   */
  where: Prisma.PostedTradeWhereUniqueInput
}

/**
 * PostedTrade deleteMany
 */
export type PostedTradeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PostedTrades to delete
   */
  where?: Prisma.PostedTradeWhereInput
  /**
   * Limit how many PostedTrades to delete.
   */
  limit?: number
}

/**
 * PostedTrade.asset
 */
export type PostedTrade$assetArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  where?: Prisma.AssetWhereInput
}

/**
 * PostedTrade without action
 */
export type PostedTradeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostedTrade
   */
  select?: Prisma.PostedTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostedTrade
   */
  omit?: Prisma.PostedTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostedTradeInclude<ExtArgs> | null
}
