
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StakingOption` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StakingOption
 * 
 */
export type StakingOptionModel = runtime.Types.Result.DefaultSelection<Prisma.$StakingOptionPayload>

export type AggregateStakingOption = {
  _count: StakingOptionCountAggregateOutputType | null
  _avg: StakingOptionAvgAggregateOutputType | null
  _sum: StakingOptionSumAggregateOutputType | null
  _min: StakingOptionMinAggregateOutputType | null
  _max: StakingOptionMaxAggregateOutputType | null
}

export type StakingOptionAvgAggregateOutputType = {
  roi: number | null
  duration: number | null
  minimum: number | null
  maximum: number | null
}

export type StakingOptionSumAggregateOutputType = {
  roi: number | null
  duration: number | null
  minimum: number | null
  maximum: number | null
}

export type StakingOptionMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  roi: number | null
  duration: number | null
  minimum: number | null
  maximum: number | null
  enabled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StakingOptionMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  roi: number | null
  duration: number | null
  minimum: number | null
  maximum: number | null
  enabled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StakingOptionCountAggregateOutputType = {
  id: number
  name: number
  description: number
  roi: number
  duration: number
  minimum: number
  maximum: number
  enabled: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StakingOptionAvgAggregateInputType = {
  roi?: true
  duration?: true
  minimum?: true
  maximum?: true
}

export type StakingOptionSumAggregateInputType = {
  roi?: true
  duration?: true
  minimum?: true
  maximum?: true
}

export type StakingOptionMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  roi?: true
  duration?: true
  minimum?: true
  maximum?: true
  enabled?: true
  createdAt?: true
  updatedAt?: true
}

export type StakingOptionMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  roi?: true
  duration?: true
  minimum?: true
  maximum?: true
  enabled?: true
  createdAt?: true
  updatedAt?: true
}

export type StakingOptionCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  roi?: true
  duration?: true
  minimum?: true
  maximum?: true
  enabled?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StakingOptionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StakingOption to aggregate.
   */
  where?: Prisma.StakingOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StakingOptions to fetch.
   */
  orderBy?: Prisma.StakingOptionOrderByWithRelationInput | Prisma.StakingOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StakingOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StakingOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StakingOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StakingOptions
  **/
  _count?: true | StakingOptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StakingOptionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StakingOptionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StakingOptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StakingOptionMaxAggregateInputType
}

export type GetStakingOptionAggregateType<T extends StakingOptionAggregateArgs> = {
      [P in keyof T & keyof AggregateStakingOption]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStakingOption[P]>
    : Prisma.GetScalarType<T[P], AggregateStakingOption[P]>
}




export type StakingOptionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StakingOptionWhereInput
  orderBy?: Prisma.StakingOptionOrderByWithAggregationInput | Prisma.StakingOptionOrderByWithAggregationInput[]
  by: Prisma.StakingOptionScalarFieldEnum[] | Prisma.StakingOptionScalarFieldEnum
  having?: Prisma.StakingOptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StakingOptionCountAggregateInputType | true
  _avg?: StakingOptionAvgAggregateInputType
  _sum?: StakingOptionSumAggregateInputType
  _min?: StakingOptionMinAggregateInputType
  _max?: StakingOptionMaxAggregateInputType
}

export type StakingOptionGroupByOutputType = {
  id: string
  name: string
  description: string | null
  roi: number
  duration: number
  minimum: number
  maximum: number | null
  enabled: boolean
  createdAt: Date
  updatedAt: Date
  _count: StakingOptionCountAggregateOutputType | null
  _avg: StakingOptionAvgAggregateOutputType | null
  _sum: StakingOptionSumAggregateOutputType | null
  _min: StakingOptionMinAggregateOutputType | null
  _max: StakingOptionMaxAggregateOutputType | null
}

type GetStakingOptionGroupByPayload<T extends StakingOptionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StakingOptionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StakingOptionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StakingOptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StakingOptionGroupByOutputType[P]>
      }
    >
  >



export type StakingOptionWhereInput = {
  AND?: Prisma.StakingOptionWhereInput | Prisma.StakingOptionWhereInput[]
  OR?: Prisma.StakingOptionWhereInput[]
  NOT?: Prisma.StakingOptionWhereInput | Prisma.StakingOptionWhereInput[]
  id?: Prisma.StringFilter<"StakingOption"> | string
  name?: Prisma.StringFilter<"StakingOption"> | string
  description?: Prisma.StringNullableFilter<"StakingOption"> | string | null
  roi?: Prisma.FloatFilter<"StakingOption"> | number
  duration?: Prisma.IntFilter<"StakingOption"> | number
  minimum?: Prisma.FloatFilter<"StakingOption"> | number
  maximum?: Prisma.FloatNullableFilter<"StakingOption"> | number | null
  enabled?: Prisma.BoolFilter<"StakingOption"> | boolean
  createdAt?: Prisma.DateTimeFilter<"StakingOption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StakingOption"> | Date | string
}

export type StakingOptionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  roi?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  minimum?: Prisma.SortOrder
  maximum?: Prisma.SortOrderInput | Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StakingOptionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StakingOptionWhereInput | Prisma.StakingOptionWhereInput[]
  OR?: Prisma.StakingOptionWhereInput[]
  NOT?: Prisma.StakingOptionWhereInput | Prisma.StakingOptionWhereInput[]
  name?: Prisma.StringFilter<"StakingOption"> | string
  description?: Prisma.StringNullableFilter<"StakingOption"> | string | null
  roi?: Prisma.FloatFilter<"StakingOption"> | number
  duration?: Prisma.IntFilter<"StakingOption"> | number
  minimum?: Prisma.FloatFilter<"StakingOption"> | number
  maximum?: Prisma.FloatNullableFilter<"StakingOption"> | number | null
  enabled?: Prisma.BoolFilter<"StakingOption"> | boolean
  createdAt?: Prisma.DateTimeFilter<"StakingOption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StakingOption"> | Date | string
}, "id">

export type StakingOptionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  roi?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  minimum?: Prisma.SortOrder
  maximum?: Prisma.SortOrderInput | Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StakingOptionCountOrderByAggregateInput
  _avg?: Prisma.StakingOptionAvgOrderByAggregateInput
  _max?: Prisma.StakingOptionMaxOrderByAggregateInput
  _min?: Prisma.StakingOptionMinOrderByAggregateInput
  _sum?: Prisma.StakingOptionSumOrderByAggregateInput
}

export type StakingOptionScalarWhereWithAggregatesInput = {
  AND?: Prisma.StakingOptionScalarWhereWithAggregatesInput | Prisma.StakingOptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.StakingOptionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StakingOptionScalarWhereWithAggregatesInput | Prisma.StakingOptionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StakingOption"> | string
  name?: Prisma.StringWithAggregatesFilter<"StakingOption"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"StakingOption"> | string | null
  roi?: Prisma.FloatWithAggregatesFilter<"StakingOption"> | number
  duration?: Prisma.IntWithAggregatesFilter<"StakingOption"> | number
  minimum?: Prisma.FloatWithAggregatesFilter<"StakingOption"> | number
  maximum?: Prisma.FloatNullableWithAggregatesFilter<"StakingOption"> | number | null
  enabled?: Prisma.BoolWithAggregatesFilter<"StakingOption"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StakingOption"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"StakingOption"> | Date | string
}

export type StakingOptionCreateInput = {
  id?: string
  name: string
  description?: string | null
  roi: number
  duration: number
  minimum: number
  maximum?: number | null
  enabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StakingOptionUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  roi: number
  duration: number
  minimum: number
  maximum?: number | null
  enabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StakingOptionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  minimum?: Prisma.FloatFieldUpdateOperationsInput | number
  maximum?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StakingOptionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  minimum?: Prisma.FloatFieldUpdateOperationsInput | number
  maximum?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StakingOptionCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  roi: number
  duration: number
  minimum: number
  maximum?: number | null
  enabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StakingOptionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  minimum?: Prisma.FloatFieldUpdateOperationsInput | number
  maximum?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StakingOptionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  minimum?: Prisma.FloatFieldUpdateOperationsInput | number
  maximum?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StakingOptionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  minimum?: Prisma.SortOrder
  maximum?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StakingOptionAvgOrderByAggregateInput = {
  roi?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  minimum?: Prisma.SortOrder
  maximum?: Prisma.SortOrder
}

export type StakingOptionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  minimum?: Prisma.SortOrder
  maximum?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StakingOptionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  minimum?: Prisma.SortOrder
  maximum?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StakingOptionSumOrderByAggregateInput = {
  roi?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  minimum?: Prisma.SortOrder
  maximum?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type StakingOptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  roi?: boolean
  duration?: boolean
  minimum?: boolean
  maximum?: boolean
  enabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["stakingOption"]>

export type StakingOptionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  roi?: boolean
  duration?: boolean
  minimum?: boolean
  maximum?: boolean
  enabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["stakingOption"]>

export type StakingOptionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  roi?: boolean
  duration?: boolean
  minimum?: boolean
  maximum?: boolean
  enabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["stakingOption"]>

export type StakingOptionSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  roi?: boolean
  duration?: boolean
  minimum?: boolean
  maximum?: boolean
  enabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StakingOptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "roi" | "duration" | "minimum" | "maximum" | "enabled" | "createdAt" | "updatedAt", ExtArgs["result"]["stakingOption"]>

export type $StakingOptionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StakingOption"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    roi: number
    duration: number
    minimum: number
    maximum: number | null
    enabled: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["stakingOption"]>
  composites: {}
}

export type StakingOptionGetPayload<S extends boolean | null | undefined | StakingOptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload, S>

export type StakingOptionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StakingOptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StakingOptionCountAggregateInputType | true
  }

export interface StakingOptionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StakingOption'], meta: { name: 'StakingOption' } }
  /**
   * Find zero or one StakingOption that matches the filter.
   * @param {StakingOptionFindUniqueArgs} args - Arguments to find a StakingOption
   * @example
   * // Get one StakingOption
   * const stakingOption = await prisma.stakingOption.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StakingOptionFindUniqueArgs>(args: Prisma.SelectSubset<T, StakingOptionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StakingOptionClient<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StakingOption that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StakingOptionFindUniqueOrThrowArgs} args - Arguments to find a StakingOption
   * @example
   * // Get one StakingOption
   * const stakingOption = await prisma.stakingOption.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StakingOptionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StakingOptionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StakingOptionClient<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StakingOption that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakingOptionFindFirstArgs} args - Arguments to find a StakingOption
   * @example
   * // Get one StakingOption
   * const stakingOption = await prisma.stakingOption.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StakingOptionFindFirstArgs>(args?: Prisma.SelectSubset<T, StakingOptionFindFirstArgs<ExtArgs>>): Prisma.Prisma__StakingOptionClient<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StakingOption that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakingOptionFindFirstOrThrowArgs} args - Arguments to find a StakingOption
   * @example
   * // Get one StakingOption
   * const stakingOption = await prisma.stakingOption.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StakingOptionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StakingOptionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StakingOptionClient<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StakingOptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakingOptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StakingOptions
   * const stakingOptions = await prisma.stakingOption.findMany()
   * 
   * // Get first 10 StakingOptions
   * const stakingOptions = await prisma.stakingOption.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stakingOptionWithIdOnly = await prisma.stakingOption.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StakingOptionFindManyArgs>(args?: Prisma.SelectSubset<T, StakingOptionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StakingOption.
   * @param {StakingOptionCreateArgs} args - Arguments to create a StakingOption.
   * @example
   * // Create one StakingOption
   * const StakingOption = await prisma.stakingOption.create({
   *   data: {
   *     // ... data to create a StakingOption
   *   }
   * })
   * 
   */
  create<T extends StakingOptionCreateArgs>(args: Prisma.SelectSubset<T, StakingOptionCreateArgs<ExtArgs>>): Prisma.Prisma__StakingOptionClient<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StakingOptions.
   * @param {StakingOptionCreateManyArgs} args - Arguments to create many StakingOptions.
   * @example
   * // Create many StakingOptions
   * const stakingOption = await prisma.stakingOption.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StakingOptionCreateManyArgs>(args?: Prisma.SelectSubset<T, StakingOptionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StakingOptions and returns the data saved in the database.
   * @param {StakingOptionCreateManyAndReturnArgs} args - Arguments to create many StakingOptions.
   * @example
   * // Create many StakingOptions
   * const stakingOption = await prisma.stakingOption.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StakingOptions and only return the `id`
   * const stakingOptionWithIdOnly = await prisma.stakingOption.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StakingOptionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StakingOptionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StakingOption.
   * @param {StakingOptionDeleteArgs} args - Arguments to delete one StakingOption.
   * @example
   * // Delete one StakingOption
   * const StakingOption = await prisma.stakingOption.delete({
   *   where: {
   *     // ... filter to delete one StakingOption
   *   }
   * })
   * 
   */
  delete<T extends StakingOptionDeleteArgs>(args: Prisma.SelectSubset<T, StakingOptionDeleteArgs<ExtArgs>>): Prisma.Prisma__StakingOptionClient<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StakingOption.
   * @param {StakingOptionUpdateArgs} args - Arguments to update one StakingOption.
   * @example
   * // Update one StakingOption
   * const stakingOption = await prisma.stakingOption.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StakingOptionUpdateArgs>(args: Prisma.SelectSubset<T, StakingOptionUpdateArgs<ExtArgs>>): Prisma.Prisma__StakingOptionClient<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StakingOptions.
   * @param {StakingOptionDeleteManyArgs} args - Arguments to filter StakingOptions to delete.
   * @example
   * // Delete a few StakingOptions
   * const { count } = await prisma.stakingOption.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StakingOptionDeleteManyArgs>(args?: Prisma.SelectSubset<T, StakingOptionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StakingOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakingOptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StakingOptions
   * const stakingOption = await prisma.stakingOption.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StakingOptionUpdateManyArgs>(args: Prisma.SelectSubset<T, StakingOptionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StakingOptions and returns the data updated in the database.
   * @param {StakingOptionUpdateManyAndReturnArgs} args - Arguments to update many StakingOptions.
   * @example
   * // Update many StakingOptions
   * const stakingOption = await prisma.stakingOption.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StakingOptions and only return the `id`
   * const stakingOptionWithIdOnly = await prisma.stakingOption.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StakingOptionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StakingOptionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StakingOption.
   * @param {StakingOptionUpsertArgs} args - Arguments to update or create a StakingOption.
   * @example
   * // Update or create a StakingOption
   * const stakingOption = await prisma.stakingOption.upsert({
   *   create: {
   *     // ... data to create a StakingOption
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StakingOption we want to update
   *   }
   * })
   */
  upsert<T extends StakingOptionUpsertArgs>(args: Prisma.SelectSubset<T, StakingOptionUpsertArgs<ExtArgs>>): Prisma.Prisma__StakingOptionClient<runtime.Types.Result.GetResult<Prisma.$StakingOptionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StakingOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakingOptionCountArgs} args - Arguments to filter StakingOptions to count.
   * @example
   * // Count the number of StakingOptions
   * const count = await prisma.stakingOption.count({
   *   where: {
   *     // ... the filter for the StakingOptions we want to count
   *   }
   * })
  **/
  count<T extends StakingOptionCountArgs>(
    args?: Prisma.Subset<T, StakingOptionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StakingOptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StakingOption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakingOptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StakingOptionAggregateArgs>(args: Prisma.Subset<T, StakingOptionAggregateArgs>): Prisma.PrismaPromise<GetStakingOptionAggregateType<T>>

  /**
   * Group by StakingOption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakingOptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StakingOptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StakingOptionGroupByArgs['orderBy'] }
      : { orderBy?: StakingOptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StakingOptionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStakingOptionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StakingOption model
 */
readonly fields: StakingOptionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StakingOption.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StakingOptionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StakingOption model
 */
export interface StakingOptionFieldRefs {
  readonly id: Prisma.FieldRef<"StakingOption", 'String'>
  readonly name: Prisma.FieldRef<"StakingOption", 'String'>
  readonly description: Prisma.FieldRef<"StakingOption", 'String'>
  readonly roi: Prisma.FieldRef<"StakingOption", 'Float'>
  readonly duration: Prisma.FieldRef<"StakingOption", 'Int'>
  readonly minimum: Prisma.FieldRef<"StakingOption", 'Float'>
  readonly maximum: Prisma.FieldRef<"StakingOption", 'Float'>
  readonly enabled: Prisma.FieldRef<"StakingOption", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"StakingOption", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"StakingOption", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StakingOption findUnique
 */
export type StakingOptionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * Filter, which StakingOption to fetch.
   */
  where: Prisma.StakingOptionWhereUniqueInput
}

/**
 * StakingOption findUniqueOrThrow
 */
export type StakingOptionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * Filter, which StakingOption to fetch.
   */
  where: Prisma.StakingOptionWhereUniqueInput
}

/**
 * StakingOption findFirst
 */
export type StakingOptionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * Filter, which StakingOption to fetch.
   */
  where?: Prisma.StakingOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StakingOptions to fetch.
   */
  orderBy?: Prisma.StakingOptionOrderByWithRelationInput | Prisma.StakingOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StakingOptions.
   */
  cursor?: Prisma.StakingOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StakingOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StakingOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StakingOptions.
   */
  distinct?: Prisma.StakingOptionScalarFieldEnum | Prisma.StakingOptionScalarFieldEnum[]
}

/**
 * StakingOption findFirstOrThrow
 */
export type StakingOptionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * Filter, which StakingOption to fetch.
   */
  where?: Prisma.StakingOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StakingOptions to fetch.
   */
  orderBy?: Prisma.StakingOptionOrderByWithRelationInput | Prisma.StakingOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StakingOptions.
   */
  cursor?: Prisma.StakingOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StakingOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StakingOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StakingOptions.
   */
  distinct?: Prisma.StakingOptionScalarFieldEnum | Prisma.StakingOptionScalarFieldEnum[]
}

/**
 * StakingOption findMany
 */
export type StakingOptionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * Filter, which StakingOptions to fetch.
   */
  where?: Prisma.StakingOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StakingOptions to fetch.
   */
  orderBy?: Prisma.StakingOptionOrderByWithRelationInput | Prisma.StakingOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StakingOptions.
   */
  cursor?: Prisma.StakingOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StakingOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StakingOptions.
   */
  skip?: number
  distinct?: Prisma.StakingOptionScalarFieldEnum | Prisma.StakingOptionScalarFieldEnum[]
}

/**
 * StakingOption create
 */
export type StakingOptionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * The data needed to create a StakingOption.
   */
  data: Prisma.XOR<Prisma.StakingOptionCreateInput, Prisma.StakingOptionUncheckedCreateInput>
}

/**
 * StakingOption createMany
 */
export type StakingOptionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StakingOptions.
   */
  data: Prisma.StakingOptionCreateManyInput | Prisma.StakingOptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StakingOption createManyAndReturn
 */
export type StakingOptionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * The data used to create many StakingOptions.
   */
  data: Prisma.StakingOptionCreateManyInput | Prisma.StakingOptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StakingOption update
 */
export type StakingOptionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * The data needed to update a StakingOption.
   */
  data: Prisma.XOR<Prisma.StakingOptionUpdateInput, Prisma.StakingOptionUncheckedUpdateInput>
  /**
   * Choose, which StakingOption to update.
   */
  where: Prisma.StakingOptionWhereUniqueInput
}

/**
 * StakingOption updateMany
 */
export type StakingOptionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StakingOptions.
   */
  data: Prisma.XOR<Prisma.StakingOptionUpdateManyMutationInput, Prisma.StakingOptionUncheckedUpdateManyInput>
  /**
   * Filter which StakingOptions to update
   */
  where?: Prisma.StakingOptionWhereInput
  /**
   * Limit how many StakingOptions to update.
   */
  limit?: number
}

/**
 * StakingOption updateManyAndReturn
 */
export type StakingOptionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * The data used to update StakingOptions.
   */
  data: Prisma.XOR<Prisma.StakingOptionUpdateManyMutationInput, Prisma.StakingOptionUncheckedUpdateManyInput>
  /**
   * Filter which StakingOptions to update
   */
  where?: Prisma.StakingOptionWhereInput
  /**
   * Limit how many StakingOptions to update.
   */
  limit?: number
}

/**
 * StakingOption upsert
 */
export type StakingOptionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * The filter to search for the StakingOption to update in case it exists.
   */
  where: Prisma.StakingOptionWhereUniqueInput
  /**
   * In case the StakingOption found by the `where` argument doesn't exist, create a new StakingOption with this data.
   */
  create: Prisma.XOR<Prisma.StakingOptionCreateInput, Prisma.StakingOptionUncheckedCreateInput>
  /**
   * In case the StakingOption was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StakingOptionUpdateInput, Prisma.StakingOptionUncheckedUpdateInput>
}

/**
 * StakingOption delete
 */
export type StakingOptionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
  /**
   * Filter which StakingOption to delete.
   */
  where: Prisma.StakingOptionWhereUniqueInput
}

/**
 * StakingOption deleteMany
 */
export type StakingOptionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StakingOptions to delete
   */
  where?: Prisma.StakingOptionWhereInput
  /**
   * Limit how many StakingOptions to delete.
   */
  limit?: number
}

/**
 * StakingOption without action
 */
export type StakingOptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StakingOption
   */
  select?: Prisma.StakingOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StakingOption
   */
  omit?: Prisma.StakingOptionOmit<ExtArgs> | null
}
