
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserStake` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserStake
 * 
 */
export type UserStakeModel = runtime.Types.Result.DefaultSelection<Prisma.$UserStakePayload>

export type AggregateUserStake = {
  _count: UserStakeCountAggregateOutputType | null
  _avg: UserStakeAvgAggregateOutputType | null
  _sum: UserStakeSumAggregateOutputType | null
  _min: UserStakeMinAggregateOutputType | null
  _max: UserStakeMaxAggregateOutputType | null
}

export type UserStakeAvgAggregateOutputType = {
  amount: number | null
  roi: number | null
  cycleDays: number | null
}

export type UserStakeSumAggregateOutputType = {
  amount: number | null
  roi: number | null
  cycleDays: number | null
}

export type UserStakeMinAggregateOutputType = {
  id: string | null
  userId: string | null
  assetId: string | null
  amount: number | null
  roi: number | null
  cycleDays: number | null
  startDate: Date | null
  endDate: Date | null
  status: string | null
}

export type UserStakeMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  assetId: string | null
  amount: number | null
  roi: number | null
  cycleDays: number | null
  startDate: Date | null
  endDate: Date | null
  status: string | null
}

export type UserStakeCountAggregateOutputType = {
  id: number
  userId: number
  assetId: number
  amount: number
  roi: number
  cycleDays: number
  startDate: number
  endDate: number
  status: number
  _all: number
}


export type UserStakeAvgAggregateInputType = {
  amount?: true
  roi?: true
  cycleDays?: true
}

export type UserStakeSumAggregateInputType = {
  amount?: true
  roi?: true
  cycleDays?: true
}

export type UserStakeMinAggregateInputType = {
  id?: true
  userId?: true
  assetId?: true
  amount?: true
  roi?: true
  cycleDays?: true
  startDate?: true
  endDate?: true
  status?: true
}

export type UserStakeMaxAggregateInputType = {
  id?: true
  userId?: true
  assetId?: true
  amount?: true
  roi?: true
  cycleDays?: true
  startDate?: true
  endDate?: true
  status?: true
}

export type UserStakeCountAggregateInputType = {
  id?: true
  userId?: true
  assetId?: true
  amount?: true
  roi?: true
  cycleDays?: true
  startDate?: true
  endDate?: true
  status?: true
  _all?: true
}

export type UserStakeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserStake to aggregate.
   */
  where?: Prisma.UserStakeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserStakes to fetch.
   */
  orderBy?: Prisma.UserStakeOrderByWithRelationInput | Prisma.UserStakeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserStakeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserStakes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserStakes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserStakes
  **/
  _count?: true | UserStakeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserStakeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserStakeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserStakeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserStakeMaxAggregateInputType
}

export type GetUserStakeAggregateType<T extends UserStakeAggregateArgs> = {
      [P in keyof T & keyof AggregateUserStake]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserStake[P]>
    : Prisma.GetScalarType<T[P], AggregateUserStake[P]>
}




export type UserStakeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserStakeWhereInput
  orderBy?: Prisma.UserStakeOrderByWithAggregationInput | Prisma.UserStakeOrderByWithAggregationInput[]
  by: Prisma.UserStakeScalarFieldEnum[] | Prisma.UserStakeScalarFieldEnum
  having?: Prisma.UserStakeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserStakeCountAggregateInputType | true
  _avg?: UserStakeAvgAggregateInputType
  _sum?: UserStakeSumAggregateInputType
  _min?: UserStakeMinAggregateInputType
  _max?: UserStakeMaxAggregateInputType
}

export type UserStakeGroupByOutputType = {
  id: string
  userId: string
  assetId: string
  amount: number
  roi: number
  cycleDays: number
  startDate: Date
  endDate: Date
  status: string
  _count: UserStakeCountAggregateOutputType | null
  _avg: UserStakeAvgAggregateOutputType | null
  _sum: UserStakeSumAggregateOutputType | null
  _min: UserStakeMinAggregateOutputType | null
  _max: UserStakeMaxAggregateOutputType | null
}

type GetUserStakeGroupByPayload<T extends UserStakeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserStakeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserStakeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserStakeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserStakeGroupByOutputType[P]>
      }
    >
  >



export type UserStakeWhereInput = {
  AND?: Prisma.UserStakeWhereInput | Prisma.UserStakeWhereInput[]
  OR?: Prisma.UserStakeWhereInput[]
  NOT?: Prisma.UserStakeWhereInput | Prisma.UserStakeWhereInput[]
  id?: Prisma.StringFilter<"UserStake"> | string
  userId?: Prisma.StringFilter<"UserStake"> | string
  assetId?: Prisma.StringFilter<"UserStake"> | string
  amount?: Prisma.FloatFilter<"UserStake"> | number
  roi?: Prisma.FloatFilter<"UserStake"> | number
  cycleDays?: Prisma.IntFilter<"UserStake"> | number
  startDate?: Prisma.DateTimeFilter<"UserStake"> | Date | string
  endDate?: Prisma.DateTimeFilter<"UserStake"> | Date | string
  status?: Prisma.StringFilter<"UserStake"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  asset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
}

export type UserStakeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  cycleDays?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  asset?: Prisma.AssetOrderByWithRelationInput
}

export type UserStakeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserStakeWhereInput | Prisma.UserStakeWhereInput[]
  OR?: Prisma.UserStakeWhereInput[]
  NOT?: Prisma.UserStakeWhereInput | Prisma.UserStakeWhereInput[]
  userId?: Prisma.StringFilter<"UserStake"> | string
  assetId?: Prisma.StringFilter<"UserStake"> | string
  amount?: Prisma.FloatFilter<"UserStake"> | number
  roi?: Prisma.FloatFilter<"UserStake"> | number
  cycleDays?: Prisma.IntFilter<"UserStake"> | number
  startDate?: Prisma.DateTimeFilter<"UserStake"> | Date | string
  endDate?: Prisma.DateTimeFilter<"UserStake"> | Date | string
  status?: Prisma.StringFilter<"UserStake"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  asset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
}, "id">

export type UserStakeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  cycleDays?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.UserStakeCountOrderByAggregateInput
  _avg?: Prisma.UserStakeAvgOrderByAggregateInput
  _max?: Prisma.UserStakeMaxOrderByAggregateInput
  _min?: Prisma.UserStakeMinOrderByAggregateInput
  _sum?: Prisma.UserStakeSumOrderByAggregateInput
}

export type UserStakeScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserStakeScalarWhereWithAggregatesInput | Prisma.UserStakeScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserStakeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserStakeScalarWhereWithAggregatesInput | Prisma.UserStakeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserStake"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserStake"> | string
  assetId?: Prisma.StringWithAggregatesFilter<"UserStake"> | string
  amount?: Prisma.FloatWithAggregatesFilter<"UserStake"> | number
  roi?: Prisma.FloatWithAggregatesFilter<"UserStake"> | number
  cycleDays?: Prisma.IntWithAggregatesFilter<"UserStake"> | number
  startDate?: Prisma.DateTimeWithAggregatesFilter<"UserStake"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"UserStake"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"UserStake"> | string
}

export type UserStakeCreateInput = {
  id?: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
  user: Prisma.UserCreateNestedOneWithoutUserStakesInput
  asset: Prisma.AssetCreateNestedOneWithoutUserStakesInput
}

export type UserStakeUncheckedCreateInput = {
  id?: string
  userId: string
  assetId: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
}

export type UserStakeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutUserStakesNestedInput
  asset?: Prisma.AssetUpdateOneRequiredWithoutUserStakesNestedInput
}

export type UserStakeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStakeCreateManyInput = {
  id?: string
  userId: string
  assetId: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
}

export type UserStakeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStakeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStakeListRelationFilter = {
  every?: Prisma.UserStakeWhereInput
  some?: Prisma.UserStakeWhereInput
  none?: Prisma.UserStakeWhereInput
}

export type UserStakeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserStakeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  cycleDays?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type UserStakeAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  cycleDays?: Prisma.SortOrder
}

export type UserStakeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  cycleDays?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type UserStakeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  cycleDays?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type UserStakeSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  cycleDays?: Prisma.SortOrder
}

export type UserStakeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserStakeCreateWithoutUserInput, Prisma.UserStakeUncheckedCreateWithoutUserInput> | Prisma.UserStakeCreateWithoutUserInput[] | Prisma.UserStakeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserStakeCreateOrConnectWithoutUserInput | Prisma.UserStakeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserStakeCreateManyUserInputEnvelope
  connect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
}

export type UserStakeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserStakeCreateWithoutUserInput, Prisma.UserStakeUncheckedCreateWithoutUserInput> | Prisma.UserStakeCreateWithoutUserInput[] | Prisma.UserStakeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserStakeCreateOrConnectWithoutUserInput | Prisma.UserStakeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserStakeCreateManyUserInputEnvelope
  connect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
}

export type UserStakeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserStakeCreateWithoutUserInput, Prisma.UserStakeUncheckedCreateWithoutUserInput> | Prisma.UserStakeCreateWithoutUserInput[] | Prisma.UserStakeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserStakeCreateOrConnectWithoutUserInput | Prisma.UserStakeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserStakeUpsertWithWhereUniqueWithoutUserInput | Prisma.UserStakeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserStakeCreateManyUserInputEnvelope
  set?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  disconnect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  delete?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  connect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  update?: Prisma.UserStakeUpdateWithWhereUniqueWithoutUserInput | Prisma.UserStakeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserStakeUpdateManyWithWhereWithoutUserInput | Prisma.UserStakeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserStakeScalarWhereInput | Prisma.UserStakeScalarWhereInput[]
}

export type UserStakeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserStakeCreateWithoutUserInput, Prisma.UserStakeUncheckedCreateWithoutUserInput> | Prisma.UserStakeCreateWithoutUserInput[] | Prisma.UserStakeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserStakeCreateOrConnectWithoutUserInput | Prisma.UserStakeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserStakeUpsertWithWhereUniqueWithoutUserInput | Prisma.UserStakeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserStakeCreateManyUserInputEnvelope
  set?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  disconnect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  delete?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  connect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  update?: Prisma.UserStakeUpdateWithWhereUniqueWithoutUserInput | Prisma.UserStakeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserStakeUpdateManyWithWhereWithoutUserInput | Prisma.UserStakeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserStakeScalarWhereInput | Prisma.UserStakeScalarWhereInput[]
}

export type UserStakeCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.UserStakeCreateWithoutAssetInput, Prisma.UserStakeUncheckedCreateWithoutAssetInput> | Prisma.UserStakeCreateWithoutAssetInput[] | Prisma.UserStakeUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.UserStakeCreateOrConnectWithoutAssetInput | Prisma.UserStakeCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.UserStakeCreateManyAssetInputEnvelope
  connect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
}

export type UserStakeUncheckedCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.UserStakeCreateWithoutAssetInput, Prisma.UserStakeUncheckedCreateWithoutAssetInput> | Prisma.UserStakeCreateWithoutAssetInput[] | Prisma.UserStakeUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.UserStakeCreateOrConnectWithoutAssetInput | Prisma.UserStakeCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.UserStakeCreateManyAssetInputEnvelope
  connect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
}

export type UserStakeUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.UserStakeCreateWithoutAssetInput, Prisma.UserStakeUncheckedCreateWithoutAssetInput> | Prisma.UserStakeCreateWithoutAssetInput[] | Prisma.UserStakeUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.UserStakeCreateOrConnectWithoutAssetInput | Prisma.UserStakeCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.UserStakeUpsertWithWhereUniqueWithoutAssetInput | Prisma.UserStakeUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.UserStakeCreateManyAssetInputEnvelope
  set?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  disconnect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  delete?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  connect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  update?: Prisma.UserStakeUpdateWithWhereUniqueWithoutAssetInput | Prisma.UserStakeUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.UserStakeUpdateManyWithWhereWithoutAssetInput | Prisma.UserStakeUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.UserStakeScalarWhereInput | Prisma.UserStakeScalarWhereInput[]
}

export type UserStakeUncheckedUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.UserStakeCreateWithoutAssetInput, Prisma.UserStakeUncheckedCreateWithoutAssetInput> | Prisma.UserStakeCreateWithoutAssetInput[] | Prisma.UserStakeUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.UserStakeCreateOrConnectWithoutAssetInput | Prisma.UserStakeCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.UserStakeUpsertWithWhereUniqueWithoutAssetInput | Prisma.UserStakeUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.UserStakeCreateManyAssetInputEnvelope
  set?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  disconnect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  delete?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  connect?: Prisma.UserStakeWhereUniqueInput | Prisma.UserStakeWhereUniqueInput[]
  update?: Prisma.UserStakeUpdateWithWhereUniqueWithoutAssetInput | Prisma.UserStakeUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.UserStakeUpdateManyWithWhereWithoutAssetInput | Prisma.UserStakeUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.UserStakeScalarWhereInput | Prisma.UserStakeScalarWhereInput[]
}

export type UserStakeCreateWithoutUserInput = {
  id?: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
  asset: Prisma.AssetCreateNestedOneWithoutUserStakesInput
}

export type UserStakeUncheckedCreateWithoutUserInput = {
  id?: string
  assetId: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
}

export type UserStakeCreateOrConnectWithoutUserInput = {
  where: Prisma.UserStakeWhereUniqueInput
  create: Prisma.XOR<Prisma.UserStakeCreateWithoutUserInput, Prisma.UserStakeUncheckedCreateWithoutUserInput>
}

export type UserStakeCreateManyUserInputEnvelope = {
  data: Prisma.UserStakeCreateManyUserInput | Prisma.UserStakeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserStakeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserStakeWhereUniqueInput
  update: Prisma.XOR<Prisma.UserStakeUpdateWithoutUserInput, Prisma.UserStakeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserStakeCreateWithoutUserInput, Prisma.UserStakeUncheckedCreateWithoutUserInput>
}

export type UserStakeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserStakeWhereUniqueInput
  data: Prisma.XOR<Prisma.UserStakeUpdateWithoutUserInput, Prisma.UserStakeUncheckedUpdateWithoutUserInput>
}

export type UserStakeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserStakeScalarWhereInput
  data: Prisma.XOR<Prisma.UserStakeUpdateManyMutationInput, Prisma.UserStakeUncheckedUpdateManyWithoutUserInput>
}

export type UserStakeScalarWhereInput = {
  AND?: Prisma.UserStakeScalarWhereInput | Prisma.UserStakeScalarWhereInput[]
  OR?: Prisma.UserStakeScalarWhereInput[]
  NOT?: Prisma.UserStakeScalarWhereInput | Prisma.UserStakeScalarWhereInput[]
  id?: Prisma.StringFilter<"UserStake"> | string
  userId?: Prisma.StringFilter<"UserStake"> | string
  assetId?: Prisma.StringFilter<"UserStake"> | string
  amount?: Prisma.FloatFilter<"UserStake"> | number
  roi?: Prisma.FloatFilter<"UserStake"> | number
  cycleDays?: Prisma.IntFilter<"UserStake"> | number
  startDate?: Prisma.DateTimeFilter<"UserStake"> | Date | string
  endDate?: Prisma.DateTimeFilter<"UserStake"> | Date | string
  status?: Prisma.StringFilter<"UserStake"> | string
}

export type UserStakeCreateWithoutAssetInput = {
  id?: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
  user: Prisma.UserCreateNestedOneWithoutUserStakesInput
}

export type UserStakeUncheckedCreateWithoutAssetInput = {
  id?: string
  userId: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
}

export type UserStakeCreateOrConnectWithoutAssetInput = {
  where: Prisma.UserStakeWhereUniqueInput
  create: Prisma.XOR<Prisma.UserStakeCreateWithoutAssetInput, Prisma.UserStakeUncheckedCreateWithoutAssetInput>
}

export type UserStakeCreateManyAssetInputEnvelope = {
  data: Prisma.UserStakeCreateManyAssetInput | Prisma.UserStakeCreateManyAssetInput[]
  skipDuplicates?: boolean
}

export type UserStakeUpsertWithWhereUniqueWithoutAssetInput = {
  where: Prisma.UserStakeWhereUniqueInput
  update: Prisma.XOR<Prisma.UserStakeUpdateWithoutAssetInput, Prisma.UserStakeUncheckedUpdateWithoutAssetInput>
  create: Prisma.XOR<Prisma.UserStakeCreateWithoutAssetInput, Prisma.UserStakeUncheckedCreateWithoutAssetInput>
}

export type UserStakeUpdateWithWhereUniqueWithoutAssetInput = {
  where: Prisma.UserStakeWhereUniqueInput
  data: Prisma.XOR<Prisma.UserStakeUpdateWithoutAssetInput, Prisma.UserStakeUncheckedUpdateWithoutAssetInput>
}

export type UserStakeUpdateManyWithWhereWithoutAssetInput = {
  where: Prisma.UserStakeScalarWhereInput
  data: Prisma.XOR<Prisma.UserStakeUpdateManyMutationInput, Prisma.UserStakeUncheckedUpdateManyWithoutAssetInput>
}

export type UserStakeCreateManyUserInput = {
  id?: string
  assetId: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
}

export type UserStakeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  asset?: Prisma.AssetUpdateOneRequiredWithoutUserStakesNestedInput
}

export type UserStakeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStakeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStakeCreateManyAssetInput = {
  id?: string
  userId: string
  amount: number
  roi: number
  cycleDays: number
  startDate?: Date | string
  endDate: Date | string
  status?: string
}

export type UserStakeUpdateWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutUserStakesNestedInput
}

export type UserStakeUncheckedUpdateWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStakeUncheckedUpdateManyWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  roi?: Prisma.FloatFieldUpdateOperationsInput | number
  cycleDays?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UserStakeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  assetId?: boolean
  amount?: boolean
  roi?: boolean
  cycleDays?: boolean
  startDate?: boolean
  endDate?: boolean
  status?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userStake"]>

export type UserStakeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  assetId?: boolean
  amount?: boolean
  roi?: boolean
  cycleDays?: boolean
  startDate?: boolean
  endDate?: boolean
  status?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userStake"]>

export type UserStakeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  assetId?: boolean
  amount?: boolean
  roi?: boolean
  cycleDays?: boolean
  startDate?: boolean
  endDate?: boolean
  status?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userStake"]>

export type UserStakeSelectScalar = {
  id?: boolean
  userId?: boolean
  assetId?: boolean
  amount?: boolean
  roi?: boolean
  cycleDays?: boolean
  startDate?: boolean
  endDate?: boolean
  status?: boolean
}

export type UserStakeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "assetId" | "amount" | "roi" | "cycleDays" | "startDate" | "endDate" | "status", ExtArgs["result"]["userStake"]>
export type UserStakeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}
export type UserStakeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}
export type UserStakeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}

export type $UserStakePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserStake"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    asset: Prisma.$AssetPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    assetId: string
    amount: number
    roi: number
    cycleDays: number
    startDate: Date
    endDate: Date
    status: string
  }, ExtArgs["result"]["userStake"]>
  composites: {}
}

export type UserStakeGetPayload<S extends boolean | null | undefined | UserStakeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserStakePayload, S>

export type UserStakeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserStakeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserStakeCountAggregateInputType | true
  }

export interface UserStakeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserStake'], meta: { name: 'UserStake' } }
  /**
   * Find zero or one UserStake that matches the filter.
   * @param {UserStakeFindUniqueArgs} args - Arguments to find a UserStake
   * @example
   * // Get one UserStake
   * const userStake = await prisma.userStake.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserStakeFindUniqueArgs>(args: Prisma.SelectSubset<T, UserStakeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserStakeClient<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserStake that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserStakeFindUniqueOrThrowArgs} args - Arguments to find a UserStake
   * @example
   * // Get one UserStake
   * const userStake = await prisma.userStake.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserStakeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserStakeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserStakeClient<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserStake that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStakeFindFirstArgs} args - Arguments to find a UserStake
   * @example
   * // Get one UserStake
   * const userStake = await prisma.userStake.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserStakeFindFirstArgs>(args?: Prisma.SelectSubset<T, UserStakeFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserStakeClient<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserStake that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStakeFindFirstOrThrowArgs} args - Arguments to find a UserStake
   * @example
   * // Get one UserStake
   * const userStake = await prisma.userStake.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserStakeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserStakeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserStakeClient<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserStakes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStakeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserStakes
   * const userStakes = await prisma.userStake.findMany()
   * 
   * // Get first 10 UserStakes
   * const userStakes = await prisma.userStake.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userStakeWithIdOnly = await prisma.userStake.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserStakeFindManyArgs>(args?: Prisma.SelectSubset<T, UserStakeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserStake.
   * @param {UserStakeCreateArgs} args - Arguments to create a UserStake.
   * @example
   * // Create one UserStake
   * const UserStake = await prisma.userStake.create({
   *   data: {
   *     // ... data to create a UserStake
   *   }
   * })
   * 
   */
  create<T extends UserStakeCreateArgs>(args: Prisma.SelectSubset<T, UserStakeCreateArgs<ExtArgs>>): Prisma.Prisma__UserStakeClient<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserStakes.
   * @param {UserStakeCreateManyArgs} args - Arguments to create many UserStakes.
   * @example
   * // Create many UserStakes
   * const userStake = await prisma.userStake.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserStakeCreateManyArgs>(args?: Prisma.SelectSubset<T, UserStakeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserStakes and returns the data saved in the database.
   * @param {UserStakeCreateManyAndReturnArgs} args - Arguments to create many UserStakes.
   * @example
   * // Create many UserStakes
   * const userStake = await prisma.userStake.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserStakes and only return the `id`
   * const userStakeWithIdOnly = await prisma.userStake.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserStakeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserStakeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserStake.
   * @param {UserStakeDeleteArgs} args - Arguments to delete one UserStake.
   * @example
   * // Delete one UserStake
   * const UserStake = await prisma.userStake.delete({
   *   where: {
   *     // ... filter to delete one UserStake
   *   }
   * })
   * 
   */
  delete<T extends UserStakeDeleteArgs>(args: Prisma.SelectSubset<T, UserStakeDeleteArgs<ExtArgs>>): Prisma.Prisma__UserStakeClient<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserStake.
   * @param {UserStakeUpdateArgs} args - Arguments to update one UserStake.
   * @example
   * // Update one UserStake
   * const userStake = await prisma.userStake.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserStakeUpdateArgs>(args: Prisma.SelectSubset<T, UserStakeUpdateArgs<ExtArgs>>): Prisma.Prisma__UserStakeClient<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserStakes.
   * @param {UserStakeDeleteManyArgs} args - Arguments to filter UserStakes to delete.
   * @example
   * // Delete a few UserStakes
   * const { count } = await prisma.userStake.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserStakeDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserStakeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserStakes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStakeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserStakes
   * const userStake = await prisma.userStake.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserStakeUpdateManyArgs>(args: Prisma.SelectSubset<T, UserStakeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserStakes and returns the data updated in the database.
   * @param {UserStakeUpdateManyAndReturnArgs} args - Arguments to update many UserStakes.
   * @example
   * // Update many UserStakes
   * const userStake = await prisma.userStake.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserStakes and only return the `id`
   * const userStakeWithIdOnly = await prisma.userStake.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserStakeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserStakeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserStake.
   * @param {UserStakeUpsertArgs} args - Arguments to update or create a UserStake.
   * @example
   * // Update or create a UserStake
   * const userStake = await prisma.userStake.upsert({
   *   create: {
   *     // ... data to create a UserStake
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserStake we want to update
   *   }
   * })
   */
  upsert<T extends UserStakeUpsertArgs>(args: Prisma.SelectSubset<T, UserStakeUpsertArgs<ExtArgs>>): Prisma.Prisma__UserStakeClient<runtime.Types.Result.GetResult<Prisma.$UserStakePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserStakes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStakeCountArgs} args - Arguments to filter UserStakes to count.
   * @example
   * // Count the number of UserStakes
   * const count = await prisma.userStake.count({
   *   where: {
   *     // ... the filter for the UserStakes we want to count
   *   }
   * })
  **/
  count<T extends UserStakeCountArgs>(
    args?: Prisma.Subset<T, UserStakeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserStakeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserStake.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStakeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserStakeAggregateArgs>(args: Prisma.Subset<T, UserStakeAggregateArgs>): Prisma.PrismaPromise<GetUserStakeAggregateType<T>>

  /**
   * Group by UserStake.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStakeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserStakeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserStakeGroupByArgs['orderBy'] }
      : { orderBy?: UserStakeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserStakeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserStakeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserStake model
 */
readonly fields: UserStakeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserStake.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserStakeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  asset<T extends Prisma.AssetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetDefaultArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserStake model
 */
export interface UserStakeFieldRefs {
  readonly id: Prisma.FieldRef<"UserStake", 'String'>
  readonly userId: Prisma.FieldRef<"UserStake", 'String'>
  readonly assetId: Prisma.FieldRef<"UserStake", 'String'>
  readonly amount: Prisma.FieldRef<"UserStake", 'Float'>
  readonly roi: Prisma.FieldRef<"UserStake", 'Float'>
  readonly cycleDays: Prisma.FieldRef<"UserStake", 'Int'>
  readonly startDate: Prisma.FieldRef<"UserStake", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"UserStake", 'DateTime'>
  readonly status: Prisma.FieldRef<"UserStake", 'String'>
}
    

// Custom InputTypes
/**
 * UserStake findUnique
 */
export type UserStakeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * Filter, which UserStake to fetch.
   */
  where: Prisma.UserStakeWhereUniqueInput
}

/**
 * UserStake findUniqueOrThrow
 */
export type UserStakeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * Filter, which UserStake to fetch.
   */
  where: Prisma.UserStakeWhereUniqueInput
}

/**
 * UserStake findFirst
 */
export type UserStakeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * Filter, which UserStake to fetch.
   */
  where?: Prisma.UserStakeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserStakes to fetch.
   */
  orderBy?: Prisma.UserStakeOrderByWithRelationInput | Prisma.UserStakeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserStakes.
   */
  cursor?: Prisma.UserStakeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserStakes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserStakes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserStakes.
   */
  distinct?: Prisma.UserStakeScalarFieldEnum | Prisma.UserStakeScalarFieldEnum[]
}

/**
 * UserStake findFirstOrThrow
 */
export type UserStakeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * Filter, which UserStake to fetch.
   */
  where?: Prisma.UserStakeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserStakes to fetch.
   */
  orderBy?: Prisma.UserStakeOrderByWithRelationInput | Prisma.UserStakeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserStakes.
   */
  cursor?: Prisma.UserStakeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserStakes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserStakes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserStakes.
   */
  distinct?: Prisma.UserStakeScalarFieldEnum | Prisma.UserStakeScalarFieldEnum[]
}

/**
 * UserStake findMany
 */
export type UserStakeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * Filter, which UserStakes to fetch.
   */
  where?: Prisma.UserStakeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserStakes to fetch.
   */
  orderBy?: Prisma.UserStakeOrderByWithRelationInput | Prisma.UserStakeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserStakes.
   */
  cursor?: Prisma.UserStakeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserStakes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserStakes.
   */
  skip?: number
  distinct?: Prisma.UserStakeScalarFieldEnum | Prisma.UserStakeScalarFieldEnum[]
}

/**
 * UserStake create
 */
export type UserStakeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * The data needed to create a UserStake.
   */
  data: Prisma.XOR<Prisma.UserStakeCreateInput, Prisma.UserStakeUncheckedCreateInput>
}

/**
 * UserStake createMany
 */
export type UserStakeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserStakes.
   */
  data: Prisma.UserStakeCreateManyInput | Prisma.UserStakeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserStake createManyAndReturn
 */
export type UserStakeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * The data used to create many UserStakes.
   */
  data: Prisma.UserStakeCreateManyInput | Prisma.UserStakeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserStake update
 */
export type UserStakeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * The data needed to update a UserStake.
   */
  data: Prisma.XOR<Prisma.UserStakeUpdateInput, Prisma.UserStakeUncheckedUpdateInput>
  /**
   * Choose, which UserStake to update.
   */
  where: Prisma.UserStakeWhereUniqueInput
}

/**
 * UserStake updateMany
 */
export type UserStakeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserStakes.
   */
  data: Prisma.XOR<Prisma.UserStakeUpdateManyMutationInput, Prisma.UserStakeUncheckedUpdateManyInput>
  /**
   * Filter which UserStakes to update
   */
  where?: Prisma.UserStakeWhereInput
  /**
   * Limit how many UserStakes to update.
   */
  limit?: number
}

/**
 * UserStake updateManyAndReturn
 */
export type UserStakeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * The data used to update UserStakes.
   */
  data: Prisma.XOR<Prisma.UserStakeUpdateManyMutationInput, Prisma.UserStakeUncheckedUpdateManyInput>
  /**
   * Filter which UserStakes to update
   */
  where?: Prisma.UserStakeWhereInput
  /**
   * Limit how many UserStakes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserStake upsert
 */
export type UserStakeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * The filter to search for the UserStake to update in case it exists.
   */
  where: Prisma.UserStakeWhereUniqueInput
  /**
   * In case the UserStake found by the `where` argument doesn't exist, create a new UserStake with this data.
   */
  create: Prisma.XOR<Prisma.UserStakeCreateInput, Prisma.UserStakeUncheckedCreateInput>
  /**
   * In case the UserStake was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserStakeUpdateInput, Prisma.UserStakeUncheckedUpdateInput>
}

/**
 * UserStake delete
 */
export type UserStakeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
  /**
   * Filter which UserStake to delete.
   */
  where: Prisma.UserStakeWhereUniqueInput
}

/**
 * UserStake deleteMany
 */
export type UserStakeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserStakes to delete
   */
  where?: Prisma.UserStakeWhereInput
  /**
   * Limit how many UserStakes to delete.
   */
  limit?: number
}

/**
 * UserStake without action
 */
export type UserStakeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStake
   */
  select?: Prisma.UserStakeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStake
   */
  omit?: Prisma.UserStakeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStakeInclude<ExtArgs> | null
}
